const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const os=require('node:os');
const path=require('node:path');
const fs=require('node:fs');
const output=process.env.QA_OUTPUT_DIR||os.tmpdir();fs.mkdirSync(output,{recursive:true});
(async()=>{
 const browser=await chromium.launch({headless:true});
 const context=await browser.newContext({viewport:{width:1440,height:1000},timezoneId:'Asia/Ho_Chi_Minh'});
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const data=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('vinshc-demo-v2')));
 const navigate=async name=>{await page.locator(`.workspace-nav [data-page="${name}"]`).click();};
 const account=async id=>{await page.locator('#sessionDemo').click();await page.locator(`[data-session="${id}"]`).click();};
 const patient=async(id,tab)=>{await navigate('patients');await page.locator(`[data-open="${id}"]`).click();if(tab)await page.locator(`[data-tab="${tab}"]`).click();};
 const submit=async()=>{await page.locator('#moduleForm [type=submit]').click();};
 const screenshot=async name=>{await page.screenshot({path:path.join(output,`vinshc-${name}.png`),fullPage:true});};
 const responsive=async role=>{await navigate('workspace');await screenshot(role);await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,role+' mobile overflow');await screenshot(role+'-mobile');await page.setViewportSize({width:1440,height:1000});};
 // Public introduction cannot silently open a doctor session.
 await page.goto(process.env.QA_BASE_URL||'http://127.0.0.1:5173');await page.waitForSelector('.reference-hero');
 assert.equal(await page.locator('#role,[data-page],[data-open]').count(),0);
 await page.locator('.site-header a[href="#quy-trinh"]').click();assert.equal(await page.locator('[data-open]').count(),0);
 await screenshot('home');await page.locator('#headerPatients').click();assert.equal(await page.locator('[data-session]').count(),8);await screenshot('roles');
 await page.locator('[data-session="demo-reception"]').click();assert.equal(await page.locator('.content').getAttribute('data-role'),'reception');await responsive('reception');
 // Reception owns administrative registration and visit opening, but no clinical chart.
 await patient('BN-000128','overview');assert.deepEqual(await page.locator('[data-tab]').evaluateAll(x=>x.map(b=>b.dataset.tab)),['overview','history']);
 assert.equal(await page.locator('#closeVisit,#uploadDocument').count(),0);
 await page.locator('#editPatient').click();await page.locator('#patientForm [name=phone]').fill('0900000228');await page.locator('#patientForm .primary').click();assert.equal((await data()).patients.find(p=>p.id==='BN-000128').phone,'0900000228');
 await page.locator('[data-tab="overview"]').evaluate(b=>b.dataset.tab='exam');await page.locator('[data-tab="exam"]').click();assert.equal(await page.locator('#examForm').count(),0);
 await navigate('patients');await page.locator('#register').click();await page.locator('#registerForm [name=name]').fill('Người bệnh kiểm thử');await page.locator('#registerForm [name=dob]').fill('1995-03-10');await page.locator('#registerForm [name=phone]').fill('0900000999');await page.locator('#registerForm .primary').click();
 const testId=(await data()).patients.find(p=>p.name==='Người bệnh kiểm thử').id;
 await page.locator('#start').click();await page.locator('#startForm [name=reason]').fill('Luồng khám bằng dữ liệu giả');await page.locator('#startForm .primary').click();
 const visitId=(await data()).patients.find(p=>p.id===testId).visit.id;assert.ok(visitId);
 await navigate('appointments');await page.locator('#newAppointment').click();await page.locator('[name=patientId]').selectOption(testId);await page.locator('[name=time]').fill('2030-10-09T10:30');await submit();await page.locator('[data-arrived]').click();assert.match(await page.locator('tbody').innerText(),/Đã tiếp nhận/);
 await navigate('queue');await page.locator(`[data-queue="${testId}"]`).click();await page.locator('[name=state]').selectOption('Đang phục vụ');await submit();assert.match(await page.locator('tbody').innerText(),/Đang phục vụ/);
 // Nurse records vitals/notes and reads the doctor chart without write access.
 await account('demo-nurse');await responsive('nurse');assert.equal(await page.locator('[data-page="admin"],[data-page="appointments"]').count(),0);
 await patient(testId,'vitals');assert.equal(await page.locator('#start,#closeVisit,#editPatient').count(),0);
 for(const [name,value] of Object.entries({systolic:'80',diastolic:'90',pulse:'75',temperature:'36.7'}))await page.locator(`#vitalsForm [name=${name}]`).fill(value);
 await page.locator('#vitalsForm [type=submit]').click();assert.equal((await data()).patients.find(p=>p.id===testId).visit.vitals,undefined);
 await page.locator('[name=systolic]').fill('118');await page.locator('[name=diastolic]').fill('76');await page.locator('#vitalsForm [type=submit]').click();
 assert.match((await data()).patients.find(p=>p.id===testId).visit.vitals.author,/Điều dưỡng trình diễn/);
 await page.evaluate(()=>{window.__qaSetItem=Storage.prototype.setItem;Storage.prototype.setItem=()=>{throw Error('Quota exceeded');};});await page.locator('[name=systolic]').fill('120');await page.locator('#vitalsForm [type=submit]').click();assert.match(await page.locator('#toast').innerText(),/Bản sửa chưa được lưu/);assert.equal(await page.locator('[name=systolic]').inputValue(),'118');await page.evaluate(()=>{Storage.prototype.setItem=window.__qaSetItem;delete window.__qaSetItem;});
 await page.locator('[data-tab="exam"]').click();assert.equal(await page.locator('#examForm [type=submit]').count(),0);await page.locator('#examForm').evaluate(f=>f.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));assert.equal((await data()).patients.find(p=>p.id===testId).visit.exam,undefined);
 await page.locator('[data-tab="notes"]').click();await page.locator('#newNote').click();assert.deepEqual(await page.locator('[name=type] option').allTextContents(),['Ghi chú điều dưỡng','Bàn giao chăm sóc']);await page.locator('[name=content]').fill('Bàn giao dữ liệu chăm sóc mô phỏng');await submit();assert.match(await page.locator('.records-list').innerText(),/Điều dưỡng trình diễn/);
 await page.locator('[data-tab="orders"]').click();assert.equal(await page.locator('#newOrder').count(),0);
 await page.locator('[data-tab="documents"]').click();await page.locator('#uploadDocument').click();await page.locator('[name=file]').setInputFiles({name:'sample.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/l1sAAAAASUVORK5CYII=','base64')});await page.locator('[name=name]').fill('Tài liệu giả kiểm thử');await submit();await page.locator('[data-view-document]').click();await page.waitForSelector('.document-preview');await page.locator('[data-cancel]').click();
 // Doctor owns diagnosis, medications, orders and visit closure; vitals stay read-only.
 await account('demo-doctor');await responsive('doctor');await patient(testId,'exam');assert.equal(await page.locator('#editPatient,#start').count(),0);
 for(const [name,value] of Object.entries({history:'Bệnh sử giả lập',clinical:'Nội dung khám giả để kiểm thử',diagnosis:'Chẩn đoán mô phỏng',plan:'Dặn dò mô phỏng'}))await page.locator(`#examForm [name=${name}]`).fill(value);
 await page.locator('[name=allergyState]').selectOption('Có dị ứng');await page.locator('#examForm [type=submit]').click();assert.match(await page.locator('#examError').innerText(),/tác nhân/);
 await page.locator('[name=allergyDetail]').fill('Tác nhân và phản ứng giả lập');await page.locator('#addMed').click();
 for(const [name,value] of Object.entries({name:'Thuốc mô phỏng',directions:'Nội dung giả phục vụ kiểm thử',quantity:'1',unit:'viên'}))await page.locator(`[data-med=${name}]`).fill(value);
 await page.locator('#examForm [type=submit]').click();assert.match((await data()).patients.find(p=>p.id===testId).visit.exam.author,/Bác sĩ trình diễn/);
 await page.locator('[data-tab=meds]').click();await page.locator('#confirmPrescription').click();await page.locator('[name=confirmed]').check();await submit();assert.equal((await data()).patients.find(p=>p.id===testId).visit.prescriptions[0].status,'ready');await page.locator('#printPrescription').click();assert.match(await page.locator('#printBody').innerText(),/Thuốc mô phỏng/);await page.locator('[data-cancel]').click();
 await page.locator('[data-tab="vitals"]').click();assert.equal(await page.locator('#vitalsForm [type=submit]').count(),0);await page.locator('#vitalsForm').evaluate(f=>f.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));assert.equal((await data()).patients.find(p=>p.id===testId).visit.vitals.systolic,118);
 await page.locator('[data-tab="orders"]').click();await page.locator('#newOrder').click();await page.locator('[name=name]').fill('Dịch vụ giả kiểm thử');await page.locator('[name=reason]').fill('Kiểm tra đúng lượt');await submit();assert.equal((await data()).patients.find(p=>p.id===testId).visit.orders[0].visitId,visitId);
 await page.locator('[data-cancel-order]').click();await page.locator('[name=reason]').fill('Hủy dữ liệu chỉ định mẫu');await submit();assert.equal((await data()).patients.find(p=>p.id===testId).visit.orders[0].status,'cancelled');
 await page.locator('#newOrder').click();await page.locator('[name=assignedTo]').selectOption('demo-lab');await page.locator('[name=name]').fill('Chỉ định chờ nguồn');await page.locator('[name=reason]').fill('Mẫu thử màn hình chỉ đọc');await submit();
 await page.locator('[data-tab="tests"]').click();assert.equal(await page.locator('[data-result]').count(),0);assert.match(await page.locator('.records-list').innerText(),/Chưa nhận được/);
 await patient('BN-000130','tests');assert.match(await page.locator('.records-list').innerText(),/Nguồn kết quả giả lập/);assert.equal(await page.locator('[data-result]').count(),0);
 // Admin can configure accounts/forms but never opens a clinical chart.
 await account('demo-admin');await responsive('admin');assert.equal(await page.locator('[data-page="patients"],[data-patient],[data-tab]').count(),0);
 await page.locator('.workspace-nav [data-page="workspace"]').evaluate(b=>b.dataset.page='patients');await page.locator('.workspace-nav [data-page="patients"]').click();assert.equal(await page.locator('[data-open]').count(),0);assert.equal(await page.locator('.content').getAttribute('data-role'),'admin');
 // Re-render through another permitted admin page after the injected forbidden route attempt.
 await navigate('admin');await page.locator('#newAccount').click();await page.locator('[name=name]').fill('Nhân viên thử');await page.locator('[name=roles][value=doctor]').check();await submit();
 const staffId=(await data()).workspace.accounts.find(a=>a.name==='Nhân viên thử').id;
 await page.locator(`[data-edit-account="${staffId}"]`).click();await page.locator('[name=roles][value=doctor]').uncheck();await page.locator('[name=roles][value=nurse]').check();await submit();assert.equal((await data()).workspace.accounts.find(a=>a.id===staffId).role,'nurse');
 await page.locator(`[data-toggle-account="${staffId}"]`).click();await page.locator('[data-toggle-account="demo-doctor"]').click();await page.locator('#sessionDemo').click();assert.equal(await page.locator(`[data-session="${staffId}"],[data-session="demo-doctor"]`).count(),0);await page.locator('[data-cancel]').click();
 await page.reload();await page.locator('#headerPatients').click();assert.equal(await page.locator('[data-session="demo-doctor"]').count(),0);await page.locator('[data-session="demo-admin"]').click();await navigate('admin');await page.locator('[data-toggle-account="demo-doctor"]').click();
 await navigate('templates');
 for(const role of ['doctor','nurse']){await page.locator('#newTemplate').click();await page.locator('[name=name]').fill('Phiếu thử '+role);await page.locator('[name=targetRole]').selectOption(role);await submit();}
 const forms=(await data()).workspace.forms,doctorForm=forms.find(f=>f.name==='Phiếu thử doctor'),nurseForm=forms.find(f=>f.name==='Phiếu thử nurse');
 await navigate('settings');await page.locator('#facilityForm [name=name]').fill('Phòng khám VinSHC demo');await page.locator('#facilityForm .primary').click();assert.match(await page.locator('.clinic-context').innerText(),/Phòng khám VinSHC demo/);
 await navigate('audit');assert.match(await page.locator('tbody').innerText(),/Điều dưỡng trình diễn/);assert.match(await page.locator('tbody').innerText(),/demo-nurse/);
 // Backend session probe is admin-only, uses fake responses, and clears secrets.
 await navigate('connection');let loginOK=false;await page.route('**/openmrs/ws/rest/v1/session',route=>route.fulfill({status:loginOK?200:401,contentType:'application/json',body:loginOK?'{"authenticated":true,"user":{"uuid":"demo-test","display":"Demo QA"}}':'{}'}));
 await page.locator('[name=origin]').fill('http://127.0.0.1:5173');await page.locator('[name=username]').fill('demo');await page.locator('[name=password]').fill('not-a-real-password');await page.locator('#apiSessionForm [type=submit]').click();await page.waitForFunction(()=>document.querySelector('#apiSessionStatus')?.textContent.includes('bị từ chối'));assert.equal(await page.locator('[name=password]').inputValue(),'');
 loginOK=true;await page.locator('[name=password]').fill('not-a-real-password');await page.locator('#apiSessionForm [type=submit]').click();await page.waitForFunction(()=>document.querySelector('#apiSessionStatus')?.textContent.includes('API đã xác thực'));assert.equal(await page.locator('[name=password]').inputValue(),'');assert.doesNotMatch(await page.evaluate(()=>JSON.stringify(localStorage)),/not-a-real-password/);
 // Laboratory sees only the assigned order, not the complete chart, and owns result confirmation.
 await account('demo-lab');await responsive('lab');await navigate('lab');assert.equal(await page.locator('[data-page="patients"],[data-patient],[data-tab]').count(),0);assert.doesNotMatch(await page.locator('.content').innerText(),/Bệnh sử giả lập|Tác nhân và phản ứng giả lập|Lê Ngọc Hà/);
 const orderId=(await data()).patients.find(p=>p.id===testId).visit.orders.find(o=>o.name==='Chỉ định chờ nguồn').id;
 await page.locator(`[data-lab-result="${orderId}"]`).evaluate(b=>b.dataset.labResult='order-sample-result');await page.locator('[data-lab-result="order-sample-result"]').click();assert.equal(await page.locator('#modal').evaluate(d=>d.open),false);await navigate('lab');
 await page.locator(`[data-lab-result="${orderId}"]`).click();await page.locator('[name=value]').fill('Kết quả giả theo chỉ định được giao');await page.locator('[name=state]').selectOption('final');await page.locator('#operationForm [type=submit]').click();assert.match(await page.locator('#operationError').innerText(),/xác nhận/);
 await page.locator('[name=confirmed]').check();await page.locator('[name=file]').setInputFiles({name:'result.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/l1sAAAAASUVORK5CYII=','base64')});await page.locator('#operationForm [type=submit]').click();await page.waitForFunction(()=>!document.querySelector('#modal').open);assert.equal(await page.locator('[data-lab-result]').count(),0);assert.match((await data()).patients.find(p=>p.id===testId).visit.orders.find(o=>o.id===orderId).result.author,/KTV CLS trình diễn/);
 await page.locator('[data-print-result]').click();assert.match(await page.locator('#printBody').innerText(),/Kết quả giả theo chỉ định/);await page.locator('[data-cancel]').click();
 // Pharmacy receives a confirmed prescription snapshot and cannot change its medication lines.
 await account('demo-pharmacy');await responsive('pharmacy');await navigate('dispensing');assert.doesNotMatch(await page.locator('.content').innerText(),/Bệnh sử giả lập|Tác nhân và phản ứng giả lập/);await page.locator('[data-dispense]').click();assert.equal(await page.locator('[data-med],[name=diagnosis]').count(),0);await page.locator('[name=confirmed]').check();await page.locator('[name=note]').fill('Cấp thuốc mẫu sau đối chiếu');await page.locator('#operationForm [type=submit]').click();const dispensed=(await data()).patients.find(p=>p.id===testId).visit.prescriptions[0];assert.equal(dispensed.status,'dispensed');assert.equal(dispensed.medications[0].quantity,'1');assert.equal(await page.locator('[data-dispense]').count(),0);
 // Cashier records payments, rejects overpayment, and preserves refund/cancel history.
 await account('demo-cashier');await responsive('cashier');await navigate('billing');assert.equal(await page.locator('[data-patient],[data-tab]').count(),0);
 const createBill=async()=>{await page.locator('#newBill').click();await page.locator('[name=visitId]').selectOption(visitId);await page.locator('#operationForm [type=submit]').click();};
 await createBill();let bills=(await data()).workspace.bills,billId=bills.at(-1).id;await page.locator(`[data-pay-bill="${billId}"]`).click();await page.locator('[name=amount]').fill('50001');await page.locator('#operationForm [type=submit]').click();assert.match(await page.locator('#operationError').innerText(),/không vượt/);await page.locator('[name=amount]').fill('30000');await page.locator('#operationForm [type=submit]').click();assert.equal((await data()).workspace.bills.at(-1).status,'partial');await page.locator(`[data-pay-bill="${billId}"]`).click();await page.locator('#operationForm [type=submit]').click();assert.equal((await data()).workspace.bills.at(-1).status,'paid');
 await page.locator(`[data-print-bill="${billId}"]`).click();assert.match(await page.locator('#printBody').innerText(),/50.000/);assert.doesNotMatch(await page.locator('#printBody').innerText(),/Chẩn đoán mô phỏng/);await screenshot('receipt');await page.locator('[data-cancel]').click();
 await page.locator(`[data-refund-bill="${billId}"]`).click();await page.locator('[name=reason]').fill('Hoàn phí dữ liệu kiểm thử');await page.locator('#operationForm [type=submit]').click();assert.equal((await data()).workspace.bills.at(-1).status,'refunded');
 await createBill();billId=(await data()).workspace.bills.at(-1).id;await page.locator(`[data-pay-bill="${billId}"]`).click();await page.locator('#operationForm [type=submit]').click();
 await createBill();billId=(await data()).workspace.bills.at(-1).id;await page.locator(`[data-cancel-bill="${billId}"]`).click();await page.locator('[name=reason]').fill('Hủy phí chưa thu');await page.locator('#operationForm [type=submit]').click();assert.equal((await data()).workspace.bills.at(-1).status,'cancelled');
 await navigate('receipts');assert.match(await page.locator('tbody').innerText(),/Hoàn phí dữ liệu kiểm thử/);await navigate('prices');assert.equal(await page.locator('#newService').count(),0);
 // Manager receives aggregate measures without patient identities or detailed charts.
 await account('demo-manager');await responsive('manager');await navigate('reports');assert.doesNotMatch(await page.locator('.content').innerText(),/Người bệnh kiểm thử|Nguyễn Minh Anh|Chẩn đoán mô phỏng/);assert.match(await page.locator('tbody').innerText(),/50.000/);await page.locator('#printReport').click();assert.doesNotMatch(await page.locator('#printBody').innerText(),/Người bệnh kiểm thử/);await page.locator('[data-cancel]').click();
 // A single staff identity can hold multiple roles; switching workspace preserves that identity.
 await account('demo-admin');await navigate('prices');await page.locator('#newService').click();await page.locator('[name=name]').fill('Dịch vụ mẫu thêm mới');await page.locator('[name=price]').fill('123456');await page.locator('#operationForm [type=submit]').click();assert.equal((await data()).workspace.services.at(-1).price,123456);await navigate('admin');await page.locator(`[data-toggle-account="${staffId}"]`).click();await page.locator(`[data-edit-account="${staffId}"]`).click();await page.locator('[name=roles][value=doctor]').check();await submit();assert.deepEqual((await data()).workspace.accounts.find(a=>a.id===staffId).roles,['nurse','doctor']);
 await page.locator('#sessionDemo').click();await page.locator(`[data-session="${staffId}"][data-session-role="nurse"]`).click();assert.equal(await page.locator('#workspaceRole option').count(),2);await page.locator('#workspaceRole').selectOption('doctor');assert.equal(await page.locator('.content').getAttribute('data-role'),'doctor');await patient(testId,'vitals');assert.equal(await page.locator('#vitalsForm [type=submit]').count(),1);
 // Configuring a clinic without a nurse allows its doctor to record vitals; pharmacy can be disabled.
 await account('demo-admin');await navigate('settings');await page.locator('[name=hasNurse]').uncheck();await page.locator('[name=hasPharmacy]').uncheck();await page.locator('#facilityForm .primary').click();await account('demo-doctor');await patient(testId,'vitals');assert.equal(await page.locator('#vitalsForm [type=submit]').count(),1);await account('demo-pharmacy');await navigate('dispensing');assert.match(await page.locator('.module-notice').innerText(),/tắt quầy thuốc/);assert.equal(await page.locator('[data-dispense]').count(),0);
 await account('demo-admin');await navigate('settings');await page.locator('[name=hasNurse]').check();await page.locator('[name=hasPharmacy]').check();await page.locator('#facilityForm .primary').click();
 // Forms target a single writing role; a nurse cannot fill a doctor form by changing a button attribute.
 await account('demo-nurse');await navigate('templates');assert.doesNotMatch(await page.locator('.template-grid').innerText(),/Phiếu thử doctor/);assert.equal(await page.locator('#newTemplate').count(),0);
 await patient(testId,'forms');assert.equal(await page.locator(`[data-fill-form="${doctorForm.id}"]`).count(),0);
 await page.locator(`[data-fill-form="${nurseForm.id}"]`).evaluate((b,id)=>b.dataset.fillForm=id,doctorForm.id);await page.locator(`[data-fill-form="${doctorForm.id}"]`).click();assert.equal(await page.locator('#modal').evaluate(d=>d.open),false);
 await page.locator('[data-tab="forms"]').click();await page.locator(`[data-fill-form="${nurseForm.id}"]`).click();await page.locator('[name=symptom]').fill('Bản ghi điều dưỡng thử');await submit();
 await account('demo-doctor');await navigate('templates');assert.doesNotMatch(await page.locator('.template-grid').innerText(),/Phiếu thử nurse/);
 await patient(testId,'forms');await page.locator(`[data-fill-form="${doctorForm.id}"]`).click();await page.locator('[name=symptom]').fill('Bản ghi bác sĩ thử');await submit();
 await page.locator('[data-tab=tests]').click();assert.match(await page.locator('.records-list').innerText(),/Kết quả giả theo chỉ định được giao/);await page.locator('[data-result-attachment]').click();await page.waitForSelector('.document-preview');await page.locator('[data-cancel]').click();await page.locator('#closeVisit').click();await page.locator('#confirmClose').click();assert.equal((await data()).patients.find(p=>p.id===testId).visit.status,'closed');
 for(const tab of ['exam','notes','orders','documents','forms']){await page.locator(`[data-tab="${tab}"]`).click();assert.equal(await page.locator('#examForm [type=submit],#newNote,#newOrder,#uploadDocument').count(),0);}
 assert.equal(await page.locator('[data-fill-form]:not([disabled])').count(),0);
 await account('demo-nurse');await patient(testId,'vitals');assert.equal(await page.locator('#vitalsForm [type=submit]').count(),0);
 await account('demo-reception');await patient(testId,'history');assert.doesNotMatch(await page.locator('.content').innerText(),/Bệnh sử giả lập|Bản ghi bác sĩ thử|Tài liệu giả kiểm thử|Tác nhân và phản ứng giả lập/);
 await page.locator('[data-tab="overview"]').click();await page.locator('#start').click();await page.locator('#startForm [name=reason]').fill('Lượt mới giả lập');await page.locator('#startForm .primary').click();const reopened=(await data()).patients.find(p=>p.id===testId);assert.notEqual(reopened.visit.id,visitId);assert.equal(reopened.history[0].id,visitId);assert.equal(reopened.history[0].exam.medications[0].name,'Thuốc mô phỏng');
 await page.reload();assert.equal(await page.locator('[data-page]').count(),0);await page.locator('#headerPatients').click();await page.locator('[data-session="demo-doctor"]').click();await patient(testId,'history');assert.match(await page.locator('.timeline').innerText(),/Thuốc mô phỏng/);
 await page.locator('#logout').click();assert.equal(await page.locator('[data-page],[data-open]').count(),0);await page.setViewportSize({width:390,height:844});await screenshot('home-mobile');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 assert.deepEqual(errors,[]);console.log('PASS: eight role workspaces, scoped laboratory results, dispensing, billing/refund/cancellation, aggregate reports, multi-role accounts, facility variants, end-to-end reception/nurse/doctor handoff, admin isolation, account lock/role changes, form audience, storage failure rollback, report attachment viewing, denied routes/tabs/writes, read-only results/closed visits, history, persistence, files, session errors, all eight desktop/mobile layouts.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
