export function landingPage(icon){
 const features=[
  ['users','Tiếp nhận','Đúng người, đúng hồ sơ'],['clock','Lịch hẹn','Sắp xếp từng lượt khám'],['heart','Chăm sóc','Theo dõi sinh hiệu'],['file','Cận lâm sàng','Kết nối chỉ định, kết quả'],['shield','Đơn thuốc','Phối hợp theo nhiệm vụ'],
 ];
 const services=[
  ['medical-records.jpg','Ghi hồ sơ tại buổi khám','Tiếp nhận & hồ sơ','Thông tin người bệnh rõ ràng từ lần tiếp nhận đầu tiên.'],
  ['vital-signs.jpg','Nhân viên y tế đo huyết áp','Sinh hiệu & chăm sóc','Chỉ số, thời điểm đo và người thực hiện cùng một lượt khám.'],
  ['consultation.jpg','Bác sĩ trao đổi với người bệnh','Khám ngoại trú','Bệnh sử, chẩn đoán và kế hoạch chăm sóc được kết nối.'],
  ['laboratory.jpg','Nhân viên phòng xét nghiệm','Chỉ định & kết quả','Theo dõi chỉ định, người được giao và nguồn kết quả.'],
  ['medication.jpg','Thuốc trong vỉ — ảnh minh họa','Đơn thuốc & cấp thuốc','Phối hợp giữa bác sĩ và quầy thuốc theo đơn đã xác nhận.'],
 ];
 return `<section class="reference-hero health-hero" id="gioi-thieu">
  <img class="hero-photo" src="assets/laboratory.jpg" alt="Nhân viên phòng xét nghiệm làm việc với thiết bị — ảnh chụp minh họa" fetchpriority="high" width="1600" height="1068">
  <div class="hero-shade"></div>
  <div class="health-hero-copy"><span class="hero-kicker">VÌ MỘT HÀNH TRÌNH CHĂM SÓC LIỀN MẠCH</span><h1>Chăm sóc hôm nay.<br><em>Hiểu rõ ngày mai.</em></h1><p>Kết nối thông tin trong từng lượt khám.<br>Để mỗi bước chăm sóc đều bắt đầu từ sự thấu hiểu.</p><div class="hero-buttons"><a class="primary" href="#tinh-nang">Khám phá VinSHC ${icon('arrow')}</a><a class="secondary-link" href="#quy-trinh">${icon('users')} Quy trình chăm sóc</a></div><div class="hero-note">${icon('shield')} Hồ sơ khám ngoại trú cho cơ sở y tế Việt Nam</div></div>
  <div class="hero-benefits"><div>${icon('file')}<span><strong>Thông tin liền mạch</strong><small>Trong từng lượt khám</small></span></div><div>${icon('shield')}<span><strong>Đúng nhiệm vụ</strong><small>Phối hợp theo vai trò</small></span></div><div>${icon('heart')}<span><strong>Lấy người bệnh làm tâm điểm</strong><small>Từ tiếp nhận đến theo dõi</small></span></div></div>
 </section>
 <div class="landing-inner">
  <section class="help-strip" data-reveal aria-label="Giới thiệu quy trình"><h2>Kết nối từng bước chăm sóc</h2><div class="help-grid">${features.map(([i,t,d])=>`<a href="#quy-trinh" data-reveal>${icon(i)}<span><strong>${t}</strong><small>${d}</small></span><b aria-hidden="true">→</b></a>`).join('')}</div></section>
  <section class="health-services" id="tinh-nang"><div class="section-heading" data-reveal><span>HỒ SƠ KHÁM NGOẠI TRÚ</span><h2>Một hồ sơ. Trọn vẹn hành trình.</h2><p>Thông tin được nối tiếp giữa các bộ phận tại phòng khám.</p></div><div class="health-services-grid">${services.map(([photo,alt,title,description])=>`<article class="health-service" data-reveal><img src="assets/${photo}" alt="${alt} — ảnh minh họa" loading="lazy" width="600" height="400"><div><h3>${title}</h3><p>${description}</p><a href="#quy-trinh" aria-label="Tìm hiểu ${title}">${icon('arrow')}</a></div></article>`).join('')}</div></section>
  <section class="care-principles" data-reveal>${[['file','Thông tin thống nhất','Theo người bệnh và lượt khám'],['users','Phối hợp chăm sóc','Theo nhiệm vụ từng bộ phận'],['clock','Tiếp nối theo dõi','Giữ lịch sử qua từng lần khám'],['shield','Đối chiếu rõ ràng','Người ghi, nguồn và thời điểm']].map(([i,t,d])=>`<div data-reveal>${icon(i)}<span><strong>${t}</strong><small>${d}</small></span></div>`).join('')}</section>
  <section class="about-health" id="ve-vinshc"><div class="about-photo" data-reveal><img src="assets/consultation.jpg" alt="Trao đổi trong buổi tư vấn y tế — ảnh chụp minh họa" loading="lazy" width="1000" height="667"><div><span>ĐIỀU CHÚNG TÔI HƯỚNG TỚI</span><strong>Thông tin rõ ràng.<br>Chăm sóc liên tục.</strong></div></div><div class="about-copy" data-reveal><span class="hero-kicker">ĐỒNG HÀNH CÙNG PHÒNG KHÁM</span><h2>Để nhân viên y tế<br>tập trung vào người bệnh.</h2><p>VinSHC kết nối các bước tiếp nhận, chăm sóc và khám ngoại trú trong cùng một hành trình.</p><ul>${['Đối chiếu người bệnh bằng mã hồ sơ và thông tin định danh','Ghi nhận chỉ số kèm đơn vị và thời điểm đo','Phân công công việc phù hợp với từng vai trò','Giữ thông tin các lần khám để tiếp tục theo dõi'].map(t=>`<li>${icon('check')}${t}</li>`).join('')}</ul><a class="secondary-link" href="#quy-trinh">Tìm hiểu quy trình ${icon('arrow')}</a></div><aside class="staff-entry" data-reveal>${icon('users')}<span>DÀNH CHO NHÂN VIÊN Y TẾ</span><h3>Mỗi vai trò,<br>một nhiệm vụ rõ ràng.</h3><p>Tiếp đón, điều dưỡng, bác sĩ, KTV, thu ngân, quầy thuốc, quản lý và quản trị phối hợp trong từng lượt khám.</p><button data-workspace="staff">Vào phòng khám ${icon('arrow')}</button><small>Bản trình diễn · Dữ liệu giả</small></aside></section>
  <section class="landing-workflow" id="quy-trinh"><div class="section-heading" data-reveal><span>QUY TRÌNH KHÁM NGOẠI TRÚ</span><h2>Liền mạch từ lần tiếp nhận đầu tiên.</h2><p>Từng bộ phận tiếp nối thông tin để chăm sóc và theo dõi.</p></div><div class="workflow-steps">${[['Tiếp nhận','Đối chiếu hồ sơ, mở lượt và điều phối.'],['Chăm sóc','Ghi sinh hiệu và sàng lọc ban đầu.'],['Thăm khám','Khai thác bệnh sử, khám và chỉ định.'],['Cận lâm sàng','Thực hiện chỉ định và trả kết quả nếu cần.'],['Điều trị','Ghi chẩn đoán, đơn thuốc và hẹn tái khám.'],['Hoàn tất','Thu phí, cấp thuốc và lưu lịch sử theo quy trình.']].map(([t,d],i)=>`<article data-reveal><span>0${i+1}</span><h3>${t}</h3><p>${d}</p></article>`).join('')}</div></section>
  <section class="care-band" data-reveal><div>${icon('heart')}<span><small>VINSHC · HỒ SƠ KHÁM NGOẠI TRÚ</small><h2>Cùng tiếp nối hành trình chăm sóc.</h2></span></div><button data-workspace="staff">Vào phòng khám ${icon('arrow')}</button></section>
 </div>`;
}

export function landingFooter(){return `<footer class="health-footer"><div><a class="site-brand" href="#gioi-thieu"><span class="logo-plus">✚</span><strong>VinSHC</strong></a><p>Hồ sơ thống nhất.<br>Chăm sóc liên tục.</p></div><div><strong>Khám phá</strong><a href="#gioi-thieu">Giới thiệu</a><a href="#tinh-nang">Tính năng</a><a href="#quy-trinh">Quy trình chăm sóc</a></div><div><strong>VinSHC</strong><a href="#ve-vinshc">Về nền tảng</a><button data-workspace="staff">Không gian nhân viên →</button><span>Tiếng Việt · Khám ngoại trú</span></div><div><strong>Thông tin bản trình diễn</strong><p>Dữ liệu giả để kiểm tra giao diện.<br>Ảnh chụp minh họa từ Pexels.</p><a href="assets/ASSET_SOURCES.md" target="_blank" rel="noopener">Nguồn ảnh</a></div><small>VinSHC · Nền tảng hồ sơ khám ngoại trú</small></footer>`;}
