import { authenticateSession } from './api.js';
import { canWriteVisit, createOrder, recordResult, validateAppointment, validateFormDefinition, ROLE_PERMISSIONS } from './workflow.js';

export function createModules(ctx){
 const {repo,state,esc,fmt,icon,can,selected,render,persist,toast,openDialog,localDate,roles}=ctx;
 const ws=()=>repo.workspace;
 const allVisits=p=>[...(p.visit?[p.visit]:[]),...p.history];
 const writable=p=>canWriteVisit(p);
 const heading=(title,description,action='')=>`<div class="heading"><div><div class="eyebrow">VINSHC / KHÔNG GIAN NGHIỆP VỤ</div><h1>${title}</h1><p>${description}</p></div>${action}</div>`;
 const empty=text=>`<div class="empty">${text}</div>`;
 const btn=(id,text,enabled=true)=>`<button class="primary" id="${id}" ${!enabled?'disabled':''}>${icon('plus')}${text}</button>`;
 const options=(list,current)=>list.map(x=>`<option value="${esc(x)}" ${x===current?'selected':''}>${esc(x)}</option>`).join('');
 const author=()=>roles[state.role]+' (phiên demo)';
 const meta=v=>`<div class="record-meta">${esc(v.author||'Dữ liệu mẫu')} · ${v.recorded?fmt(v.recorded):v.created?fmt(v.created):''} · ${esc(v.visitId||'')}</div>`;
 const table=(headers,rows)=>`<div class="table-scroll"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows||`<tr><td colspan="${headers.length}">${empty('Chưa có dữ liệu trong mục này.')}</td></tr>`}</tbody></table></div>`;
 const section=(title,body,action='',subtitle='')=>`<section class="panel"><div class="panel-header"><div><h2>${title}</h2>${subtitle?`<small>${subtitle}</small>`:''}</div>${action}</div>${body}</section>`;
 const patientLink=p=>`<button class="link-button" data-patient="${esc(p.id)}">${esc(p.name)}</button><small class="record-meta">${esc(p.id)}</small>`;
 const badge=(text,c='')=>`<span class="badge ${c}">${text}</span>`;
 const formDialog=(title,description,body,submit,handler)=>{
  openDialog(`<h2>${title}</h2><p>${description}</p><form id="moduleForm"><div class="form-grid">${body}</div><p class="error" id="moduleError" role="alert"></p><div class="form-actions"><button type="button" data-cancel>Hủy</button><button class="primary" type="submit">${submit}</button></div></form>`);
  document.querySelector('#moduleForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget;const button=form.querySelector('[type=submit]');button.disabled=true;try{await handler(Object.fromEntries(new FormData(form)),form);document.querySelector('#modal').close();}catch(error){document.querySelector('#moduleError').textContent=error.message||'Không thể lưu.';}finally{button.disabled=false;}};
 };
 const input=(name,label,value='',extra='')=>`<label>${label}<input name="${name}" value="${esc(value)}" ${extra}></label>`;
 const area=(name,label,value='',extra='')=>`<label class="full">${label}<textarea name="${name}" ${extra}>${esc(value)}</textarea></label>`;
 const select=(name,label,choices,current)=>`<label>${label}<select name="${name}">${options(choices,current)}</select></label>`;
 const visitHint=p=>!writable(p)?'<div class="module-notice">Lượt khám đã kết thúc hoặc chưa mở. Có thể xem dữ liệu; mở lượt mới để ghi nhận.</div>':'';
 const clinicalView=p=>['doctor','nurse','admin'].includes(state.role);
 const modules=[['patients','Hồ sơ'],['active','Lượt đang khám'],['queue','Hàng đợi'],['appointments','Lịch hẹn'],['history','Lịch sử'],['templates','Biểu mẫu'],['admin','Quản trị'],['connection','Phiên OpenMRS']];
 function navigation(){return `<div class="workspace-nav" aria-label="Các module phòng khám">${modules.filter(([p])=>p!=='admin'||can('admin')).map(([p,n])=>`<button data-page="${p}" class="${state.page===p?'active':''}">${n}</button>`).join('')}<span class="workspace-mode">${icon('shield')} Dữ liệu giả · ${roles[state.role]}</span><button id="sessionDemo" class="session-button">Đổi phiên demo</button></div>`;}
 function isPage(p){return ['active','queue','appointments','templates','admin','connection'].includes(p);}
 function page(){if(state.page==='connection')return connection();if(state.page==='appointments')return appointments();if(state.page==='active')return active();if(state.page==='queue')return queue();if(state.page==='templates')return templates();return administration();}
 function connection(){return heading('Đăng nhập OpenMRS','Kiểm tra phiên backend; không chuyển dữ liệu demo thành hồ sơ thật.')+`<div class="workspace"><section class="panel form-card"><h3>Phiên làm việc tại cơ sở</h3><p class="readonly">Nhập tài khoản của instance local. Thông tin đăng nhập chỉ dùng cho một request, không lưu trong trình duyệt.</p><form id="apiSessionForm"><div class="form-grid">${input('origin','Địa chỉ gateway local *','http://127.0.0.1:8080','type="url" required')}${input('username','Tên đăng nhập *','','required autocomplete="username"')}${input('password','Mật khẩu *','','type="password" required autocomplete="current-password"')}<label>Cơ sở demo<input value="VinSHC Development Clinic" disabled></label></div><p id="apiSessionStatus" role="status" class="readonly"></p><div class="form-actions"><button class="primary" type="submit">Kiểm tra đăng nhập</button></div></form></section><aside class="panel side-section"><h3>Hai nguồn dữ liệu riêng biệt</h3><p class="readonly">Các màn hình phòng khám hiện dùng dữ liệu giả. Đăng nhập thành công ở đây chỉ xác nhận phiên API local, chưa đọc/ghi hồ sơ backend.</p><p class="readonly">Quyền và location thực tế phải lấy từ OpenMRS khi triển khai adapter. Cần gateway cho phép origin của frontend hoặc reverse proxy cùng origin.</p></aside></div>`;}
 function active(){const patients=repo.patients.filter(p=>writable(p));return heading('Lượt khám đang hoạt động','Theo dõi lượt đang mở theo cơ sở và thời điểm tiếp nhận.')+section('Danh sách lượt khám',table(['BỆNH NHÂN','LƯỢT KHÁM','TIẾP NHẬN','SINH HIỆU','PHIẾU KHÁM',''],patients.map(p=>`<tr><td>${patientLink(p)}</td><td>${esc(p.visit.id)}</td><td>${fmt(p.visit.started)}</td><td>${badge(p.visit.vitals?'Đã ghi':'Chưa ghi',p.visit.vitals?'':'wait')}</td><td>${badge(p.visit.exam?'Đã ghi':'Chưa ghi',p.visit.exam?'':'wait')}</td><td><button data-patient="${p.id}" class="link-button">Mở lượt →</button></td></tr>`).join('')));}
 function queue(){const patients=repo.patients.filter(p=>writable(p)).sort((a,b)=>new Date(a.visit.started)-new Date(b.visit.started));const rooms=['Tiếp nhận','Đo sinh hiệu','Phòng khám 01'];return heading('Hàng đợi khám','Theo dõi tiến trình tại phòng khám; thứ tự tiếp nhận không thay thế phân loại cấp cứu.')+`<div class="queue-summary">${rooms.map((r,i)=>`<div><span>BƯỚC ${i+1}</span><strong>${r}</strong><small>Phân công và trạng thái trong dữ liệu demo</small></div>`).join('')}</div>`+section('Hàng đợi đang hoạt động',table(['THỨ TỰ','BỆNH NHÂN','KHU VỰC','TRẠNG THÁI','THAO TÁC'],patients.map((p,i)=>{const q=p.visit.queue||{};return `<tr><td><span class="queue-number">${String(i+1).padStart(2,'0')}</span></td><td>${patientLink(p)}</td><td>${esc(q.room||(p.visit.vitals?'Phòng khám 01':'Đo sinh hiệu'))}</td><td>${badge(q.state||'Chờ đến lượt',q.state==='Đang phục vụ'?'exam':'wait')}</td><td>${can('queue')?`<button data-queue="${p.id}" class="link-button">Điều phối</button>`:`<button data-patient="${p.id}" class="link-button">Mở hồ sơ</button>`}</td></tr>`;}).join('')),'','Queue · Chưa kết nối module backend');}
 function appointments(){return heading('Lịch hẹn','Quản lý lịch theo bệnh nhân, dịch vụ và người khám.',can('appointments')?btn('newAppointment','Tạo lịch hẹn'):'')+section('Lịch hẹn phòng khám',table(['BỆNH NHÂN','THỜI GIAN','DỊCH VỤ / NGƯỜI KHÁM','TRẠNG THÁI',''],[...ws().appointments].sort((a,b)=>new Date(a.time)-new Date(b.time)).map(a=>{const p=repo.patients.find(p=>p.id===a.patientId);return `<tr><td>${p?patientLink(p):esc(a.patientId)}</td><td>${fmt(a.time)}</td><td>${esc(a.service)}<small class="record-meta">${esc(a.provider)}</small></td><td>${badge({scheduled:'Đã đặt',arrived:'Đã tiếp nhận',cancelled:'Đã hủy'}[a.status],a.status==='cancelled'?'neutral':'')}</td><td>${can('appointments')&&a.status==='scheduled'?`<button data-arrived="${a.id}" class="link-button">Đã đến</button><button data-cancel-appointment="${a.id}" class="link-button danger">Hủy hẹn</button>`:''}</td></tr>`;}).join('')),'','Lịch hẹn không tự mở lượt khám; cần đối chiếu bệnh nhân khi tiếp nhận.');}
 function templates(){return heading('Thư viện biểu mẫu','Biểu mẫu tiếng Việt theo lượt khám; quản lý định nghĩa và tham chiếu concept.',can('forms')?btn('newTemplate','Tạo biểu mẫu nháp'):'')+`<div class="template-grid">${ws().forms.map(f=>`<section class="panel template-card"><div class="template-icon">${icon('file')}</div><span class="article-kicker">${f.kind==='builtin'?'BIỂU MẪU GIAO DIỆN':'BẢN NHÁP TÙY CHỈNH'}</span><h2>${esc(f.name)}</h2><p>Phiên bản ${f.version} · ${f.kind==='builtin'?'Cấu trúc khám/sinh hiệu hiện có':`${f.fields.length} trường`}</p><small>Chưa xuất bản lên O3 Forms / Initializer</small><button data-preview-form="${f.id}" class="link-button">Xem cấu trúc →</button></section>`).join('')}</div><div class="module-notice">Form builder hiện tạo bản nháp và xem trước. UUID, phiên bản schema O3 và mapping metadata cần được người 1/3/4 xác nhận trước khi nạp backend.</div>`;}
 function administration(){if(!can('admin'))return heading('Không có quyền truy cập','Chỉ quản trị được xem màn hình này.');return heading('Quản trị phòng khám','Tài khoản demo, ma trận thao tác và nhật ký giao diện.',btn('newAccount','Thêm tài khoản demo'))+section('Tài khoản trình diễn',table(['TÀI KHOẢN','VAI TRÒ','TRẠNG THÁI',''],ws().accounts.map(a=>`<tr><td>${esc(a.name)}<small class="record-meta">${esc(a.id)}</small></td><td>${roles[a.role]}</td><td>${badge(a.active?'Đang hoạt động':'Đã khóa',a.active?'':'neutral')}</td><td>${a.id!=='demo-admin'?`<button class="link-button" data-toggle-account="${a.id}">${a.active?'Khóa':'Mở khóa'}</button>`:'Tài khoản demo gốc'}</td></tr>`).join('')))+`<div style="height:20px"></div>`+section('Ma trận thao tác frontend',table(['VAI TRÒ','THAO TÁC'],Object.entries(ROLE_PERMISSIONS).map(([r,actions])=>`<tr><td>${roles[r]}</td><td class="wrap-cell">${actions.map(a=>({register:'Tiếp nhận',appointments:'Lịch hẹn',queue:'Điều phối',vitals:'Sinh hiệu',exam:'Khám',notes:'Ghi chú',orders:'Chỉ định',documents:'Tài liệu',results:'Nhập kết quả mẫu',admin:'Quản trị',forms:'Biểu mẫu'}[a])).join(' · ')}</td></tr>`).join('')),'','Đây là ma trận demo đề xuất, chưa thay thế privilege / authorization của OpenMRS.')+`<div style="height:20px"></div>`+section('Nhật ký thao tác demo',table(['THỜI ĐIỂM','NGƯỜI THỰC HIỆN','THAO TÁC'],ws().audit.slice(0,20).map(a=>`<tr><td>${fmt(a.time)}</td><td>${esc(a.actor)}</td><td class="wrap-cell">${esc(a.action)}</td></tr>`).join('')),'','Nhật ký local không phải audit backend chống sửa đổi.');}
 function chart(p){if(!clinicalView(p)&&state.tab!=='documents')return empty('Vai trò lễ tân chỉ xem thông tin hành chính và lượt khám.');const method={conditions,allergies,meds,notes,orders,tests,documents,forms:patientForms}[state.tab];return method?method(p):empty('Chọn một mục hồ sơ.');}
 function conditions(p){const rows=allVisits(p).filter(v=>v.exam?.diagnosis).map(v=>`<tr><td>${esc(v.exam.diagnosis)}</td><td>${esc(v.exam.icd||'Chưa mã hóa')}</td><td>${fmt(v.exam.recorded||v.started)}</td><td>${esc(v.id)}</td><td>${badge(v.status==='closed'?'Lượt đã đóng':'Lượt đang mở',v.status==='closed'?'neutral':'')}</td></tr>`).join('');return section('Chẩn đoán theo lượt khám',table(['CHẨN ĐOÁN','ICD-10','GHI NHẬN','LƯỢT KHÁM','TRẠNG THÁI'],rows),can('exam')&&writable(p)?'<button class="primary" data-tab-target="exam">Ghi trong phiếu khám</button>':'','Mã do bác sĩ nhập; chưa đối chiếu danh mục Việt Nam.');}
 function allergies(p){const a=p.visit?.allergyAssessment||p.visit?.exam;const current=a?.state||a?.allergyState||p.allergy;return visitHint(p)+section('Dị ứng & phản ứng bất lợi',`<div class="form-card"><div class="allergy-status">${icon('shield')}<div><strong>${esc(current||'Chưa khai thác')}</strong><p>${esc(a?.detail||a?.allergyDetail||'Chưa ghi nhận chi tiết tác nhân và phản ứng.')}</p></div></div>${a?meta(a):''}<p class="readonly">“Chưa khai thác” khác với “đã khai thác và không ghi nhận”. Cần xác nhận với người bệnh trong lượt hiện tại.</p></div>`,can('exam')&&writable(p)?btn('editAllergy','Cập nhật dị ứng'):'');}
 function meds(p){return section('Thuốc đã ghi nhận',table(['THUỐC / HÀM LƯỢNG','CÁCH DÙNG','SỐ LƯỢNG','LƯỢT / THỜI ĐIỂM'],allVisits(p).flatMap(v=>(v.exam?.medications||[]).map(m=>`<tr><td>${esc(m.name)}</td><td class="wrap-cell">${esc(m.directions)}</td><td>${esc(m.quantity)} ${esc(m.unit)}</td><td>${esc(v.id)}<small class="record-meta">${fmt(v.exam.recorded||v.started)}</small></td></tr>`)).join('')),can('exam')&&writable(p)?'<button class="primary" data-tab-target="exam">Ghi đơn trong phiếu khám</button>':'','Danh sách thuốc theo đơn mẫu; không suy ra người bệnh đang sử dụng hoặc đã được cấp phát.');}
 function notes(p){const list=allVisits(p).flatMap(v=>(v.notes||[]).map(n=>({...n,visitId:v.id})));return visitHint(p)+section('Ghi chú chăm sóc',list.length?`<div class="records-list">${list.reverse().map(n=>`<article class="record-card"><span class="pill">${esc(n.type)}</span><p class="pre-wrap">${esc(n.content)}</p>${meta(n)}</article>`).join('')}</div>`:empty('Chưa có ghi chú chăm sóc.'),can('notes')&&writable(p)?btn('newNote','Thêm ghi chú'):'');}
 function orders(p){const list=allVisits(p).flatMap(v=>v.orders||[]);return visitHint(p)+section('Chỉ định dịch vụ',table(['DỊCH VỤ','LÝ DO','ƯU TIÊN','TRẠNG THÁI',''],list.map(o=>`<tr><td>${esc(o.name)}<small class="record-meta">${esc(o.type)} · ${esc(o.visitId)}</small></td><td class="wrap-cell">${esc(o.reason)}</td><td>${esc(o.priority)}</td><td>${badge({requested:'Đã chỉ định','in-progress':'Đang thực hiện',completed:'Đã có kết quả',cancelled:'Đã hủy'}[o.status],o.status==='requested'?'wait':'')}</td><td>${can('orders')&&writable(p)&&o.visitId===p.visit.id&&o.status==='requested'?`<button class="link-button danger" data-cancel-order="${o.id}">Hủy</button>`:''}</td></tr>`).join('')),can('orders')&&writable(p)?btn('newOrder','Tạo chỉ định'):'','Chỉ định mẫu; chưa gửi LIS, PACS hoặc hệ thống xét nghiệm.');}
 function tests(p){const list=allVisits(p).flatMap(v=>v.orders||[]).filter(o=>o.status!=='cancelled');return section('Kết quả xét nghiệm / báo cáo',list.length?`<div class="records-list">${list.map(o=>`<article class="record-card"><div class="record-title"><div><h3>${esc(o.name)}</h3><small>${esc(o.visitId)}</small></div>${badge(o.result?(o.result.state==='final'?'Đã xác nhận mẫu':'Sơ bộ'):'Chưa có kết quả',o.result?'':'wait')}</div>${o.result?`<p class="pre-wrap">${esc(o.result.value)} ${esc(o.result.unit)}</p><p class="readonly">Khoảng tham chiếu từ nguồn: ${esc(o.result.reference||'Chưa cung cấp')}</p>${meta(o.result)}`:'<p class="readonly">Không suy diễn kết quả khi chưa có dữ liệu nguồn.</p>'}${can('results')&&writable(p)&&o.visitId===p.visit.id?`<button data-result="${o.id}" class="link-button">${o.result?'Cập nhật kết quả mẫu':'Nhập kết quả mẫu'} →</button>`:''}</article>`).join('')}</div>`:empty('Chưa có chỉ định. Tạo chỉ định trong mục Chỉ định trước.'),'','Nhập kết quả thủ công chỉ để thử FE. Chưa có vai trò kỹ thuật viên hoặc tích hợp LIS được nghiệm thu.');}
 function documents(p){const docs=p.documents||[];return section('Tài liệu & tệp đính kèm',table(['TÀI LIỆU','LOẠI / DUNG LƯỢNG','NGUỒN / NGƯỜI GHI',''],docs.map(d=>`<tr><td>${esc(d.name)}<small class="record-meta">${esc(d.visitId)}</small></td><td>${esc(d.type)} · ${(d.size/1024).toFixed(0)} KB</td><td>${esc(d.author)}<small class="record-meta">${fmt(d.recorded)}</small></td><td><button data-view-document="${d.id}" class="link-button">Xem</button></td></tr>`).join('')),can('documents')&&writable(p)?btn('uploadDocument','Thêm tài liệu mẫu'):'','PDF / PNG / JPEG, tối đa 1 MB mỗi tệp. Chỉ tải tài liệu giả, lưu trong trình duyệt demo.');}
 function patientForms(p){return visitHint(p)+section('Biểu mẫu của lượt khám',`<div class="form-card"><div class="form-shortcuts"><button data-tab-target="vitals">Phiếu sinh hiệu →</button><button data-tab-target="exam">Phiếu khám ngoại trú →</button></div>${ws().forms.filter(f=>f.kind==='custom').map(f=>`<div class="custom-form-item"><div><strong>${esc(f.name)}</strong><small>Phiên bản ${f.version} · ${f.fields.length} trường</small></div><button data-fill-form="${f.id}" ${!writable(p)||(!can('exam')&&!can('vitals'))?'disabled':''}>Điền bản mẫu</button></div>`).join('')}<h3 style="margin-top:25px">Bản ghi biểu mẫu tùy chỉnh</h3>${allVisits(p).flatMap(v=>(v.formEntries||[]).map(entry=>`<article class="record-card"><strong>${esc(entry.name)} · v${entry.version}</strong>${entry.fields.map(f=>`<p>${esc(f.label)}: ${esc(entry.values[f.key]||'Chưa ghi nhận')} ${esc(f.unit||'')}</p>`).join('')}${meta(entry)}</article>`)).join('')||'<p class="readonly">Chưa có bản ghi biểu mẫu tùy chỉnh.</p>'}</div>`);}
 function audit(action){ws().audit.unshift({time:new Date().toISOString(),actor:author(),action});ws().audit=ws().audit.slice(0,150);}
 function previewForm(id){const f=ws().forms.find(f=>f.id===id);if(!f)return;openDialog(`<h2>${esc(f.name)}</h2><p>Phiên bản ${f.version} · Chưa xuất bản lên backend</p>${f.kind==='builtin'?`<p class="readonly">${f.id==='form-vitals'?'Huyết áp, mạch, nhiệt độ, nhịp thở, SpO₂, cân nặng, chiều cao, thời điểm đo.':'Lý do khám, bệnh sử, tiền sử, khám lâm sàng, dị ứng, chẩn đoán, ICD-10, kế hoạch và thuốc.'}</p>`:table(['TRƯỜNG','KIỂU','ĐƠN VỊ','CONCEPT UUID'],f.fields.map(v=>`<tr><td>${esc(v.label)}${v.required?' *':''}<small class="record-meta">${esc(v.key)}</small></td><td>${esc(v.type)}</td><td>${esc(v.unit||'—')}</td><td class="wrap-cell">${esc(v.concept||'Chưa mapping')}</td></tr>`).join(''))}<div class="form-actions"><button data-cancel>Đóng</button></div>`);}
 function bind(){
  document.querySelector('#apiSessionForm')?.addEventListener('submit',async e=>{
   e.preventDefault();const form=e.currentTarget,button=form.querySelector('[type=submit]'),status=document.querySelector('#apiSessionStatus');
   button.disabled=true;status.className='readonly';status.textContent='Đang xác thực phiên OpenMRS…';
   try{const result=await authenticateSession(Object.fromEntries(new FormData(form)));status.textContent='API đã xác thực tài khoản '+result.display+'. Các màn hình lâm sàng vẫn dùng dữ liệu demo.';}catch(error){status.className='error';status.textContent=error.message;}finally{form.querySelector('[name=password]').value='';button.disabled=false;}
  });
  document.querySelectorAll('[data-patient]').forEach(b=>b.onclick=()=>{state.selected=b.dataset.patient;state.tab='overview';render();});
  document.querySelectorAll('[data-tab-target]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tabTarget;render();});
  document.querySelector('#sessionDemo')?.addEventListener('click',()=>{openDialog(`<h2>Chọn phiên làm việc demo</h2><p>Tài khoản và cơ sở mô phỏng. Chưa xác thực bằng OpenMRS.</p><div class="session-list">${ws().accounts.filter(a=>a.active).map(a=>`<button data-session="${a.id}"><strong>${esc(a.name)}</strong><small>${roles[a.role]} · VinSHC Development Clinic</small></button>`).join('')}</div><div class="form-actions"><button data-cancel>Đóng</button></div>`);document.querySelectorAll('[data-session]').forEach(b=>b.onclick=()=>{state.role=ws().accounts.find(a=>a.id===b.dataset.session).role;state.page='patients';state.selected=null;document.querySelector('#modal').close();render();toast('Đã chuyển phiên demo.');});});
  document.querySelectorAll('[data-queue]').forEach(b=>b.onclick=()=>{if(!can('queue'))return;const p=repo.patients.find(p=>p.id===b.dataset.queue);formDialog('Điều phối lượt khám',p.name+' · '+p.visit.id,select('room','Khu vực',['Tiếp nhận','Đo sinh hiệu','Phòng khám 01'],p.visit.queue?.room)+select('state','Trạng thái',['Chờ đến lượt','Đang phục vụ','Tạm vắng'],p.visit.queue?.state),'Lưu điều phối',f=>{p.visit.queue=f;persist('Đã cập nhật hàng đợi mẫu.');});});
  document.querySelector('#newAppointment')?.addEventListener('click',()=>{if(!can('appointments'))return;const choices=repo.patients.map(p=>`<option value="${p.id}">${esc(p.name)} · ${p.id}</option>`).join('');formDialog('Tạo lịch hẹn','Lịch mẫu; không gửi thông báo hoặc tự mở lượt khám.',`<label>Bệnh nhân *<select name="patientId">${choices}</select></label>`+input('time','Thời gian hẹn *',localDate(new Date(Date.now()+86400000)),`type="datetime-local" required`)+select('service','Dịch vụ',['Khám ngoại trú','Tái khám','Khám sức khỏe'])+select('provider','Người khám',['Bác sĩ trình diễn 01','Bác sĩ trình diễn 02'])+area('reason','Ghi chú'),'Lưu lịch hẹn',f=>{f.time=new Date(f.time).toISOString();validateAppointment(ws().appointments,f);ws().appointments.push({...f,id:crypto.randomUUID(),status:'scheduled'});persist('Đã tạo lịch hẹn mẫu.');});});
  document.querySelectorAll('[data-arrived],[data-cancel-appointment]').forEach(b=>b.onclick=()=>{if(!can('appointments'))return;const a=ws().appointments.find(a=>a.id===(b.dataset.arrived||b.dataset.cancelAppointment));if(!a||a.status!=='scheduled')return;if(b.dataset.arrived){a.status='arrived';persist('Đã đánh dấu người bệnh đến. Mở hồ sơ để tiếp nhận.');}else{openDialog('<h2>Hủy lịch hẹn?</h2><p>Lịch được giữ lại với trạng thái đã hủy.</p><div class="form-actions"><button data-cancel>Quay lại</button><button id="confirmAppointment">Hủy lịch</button></div>');document.querySelector('#confirmAppointment').onclick=()=>{a.status='cancelled';document.querySelector('#modal').close();persist('Đã hủy lịch hẹn mẫu.');};}});
  document.querySelector('#editAllergy')?.addEventListener('click',()=>{const p=selected();if(!can('exam')||!writable(p))return;const a=p.visit.allergyAssessment||{};formDialog('Xác nhận tình trạng dị ứng',p.name+' · '+p.visit.id,select('state','Tình trạng',['Chưa khai thác','Không ghi nhận dị ứng sau khai thác','Có dị ứng'],a.state)+area('detail','Tác nhân / phản ứng',a.detail),'Lưu dị ứng',f=>{if(f.state==='Có dị ứng'&&!f.detail.trim())throw Error('Cần ghi tác nhân hoặc phản ứng dị ứng.');p.visit.allergyAssessment={...f,recorded:new Date().toISOString(),author:author()};p.allergy=f.state==='Có dị ứng'?f.detail:f.state;if(p.visit.exam){p.visit.exam.allergyState=f.state;p.visit.exam.allergyDetail=f.detail;}persist('Đã ghi nhận trạng thái dị ứng trong lượt khám.');});});
  document.querySelector('#newNote')?.addEventListener('click',()=>{const p=selected();if(!can('notes')||!writable(p))return;formDialog('Ghi chú chăm sóc',p.name+' · '+p.visit.id,select('type','Loại ghi chú',['Ghi chú lâm sàng','Ghi chú điều dưỡng','Dặn dò'])+area('content','Nội dung *','','required'),'Lưu ghi chú',f=>{if(!f.content.trim())throw Error('Cần nội dung ghi chú.');(p.visit.notes??=[]).push({...f,recorded:new Date().toISOString(),author:author()});persist('Đã lưu ghi chú theo lượt khám.');});});
  document.querySelector('#newOrder')?.addEventListener('click',()=>{const p=selected();if(!can('orders')||!writable(p))return;formDialog('Tạo chỉ định dịch vụ',p.name+' · '+p.visit.id,select('type','Nhóm dịch vụ',['Xét nghiệm','Chẩn đoán hình ảnh','Dịch vụ khác'])+input('name','Tên dịch vụ *','','required maxlength="150"')+select('priority','Mức ưu tiên',['Thường','Ưu tiên'])+area('reason','Lý do chỉ định *','','required'),'Lưu chỉ định',f=>{createOrder(p,f,author());persist('Đã tạo chỉ định mẫu. Chưa gửi tới LIS / PACS.');});});
  document.querySelectorAll('[data-cancel-order]').forEach(b=>b.onclick=()=>{const p=selected(),o=p.visit.orders.find(o=>o.id===b.dataset.cancelOrder);if(!can('orders')||!writable(p)||o.status!=='requested')return;formDialog('Hủy chỉ định','Giữ chỉ định và lý do hủy trong lịch sử.',area('reason','Lý do hủy *','','required'),'Xác nhận hủy',f=>{if(!f.reason.trim())throw Error('Cần lý do hủy.');o.status='cancelled';o.cancelReason=f.reason;o.cancelled=new Date().toISOString();persist('Đã hủy chỉ định mẫu.');});});
  document.querySelectorAll('[data-result]').forEach(b=>b.onclick=()=>{const p=selected();if(!can('results')||!writable(p))return;const o=p.visit.orders.find(o=>o.id===b.dataset.result),r=o.result||{};formDialog('Nhập kết quả mẫu',o.name+' · '+p.visit.id,area('value','Kết quả / báo cáo *',r.value,'required')+input('unit','Đơn vị (nếu có)',r.unit)+input('reference','Khoảng tham chiếu từ nguồn',r.reference)+select('state','Trạng thái kết quả',['preliminary','final'],r.state)+`<label class="full checkbox-label"><input type="checkbox" name="confirmed">Đã đối chiếu bệnh nhân, chỉ định và nguồn kết quả (demo).</label>`,'Lưu kết quả mẫu',f=>{recordResult(o,f,author());persist('Đã lưu kết quả mẫu, chưa xác thực chuyên môn.');});});
  document.querySelector('#uploadDocument')?.addEventListener('click',()=>{const p=selected();if(!can('documents')||!writable(p))return;formDialog('Thêm tài liệu mẫu',p.name+' · '+p.visit.id,input('file','Tệp PDF / PNG / JPEG *','',`type="file" accept="application/pdf,image/png,image/jpeg" required`)+input('name','Tên hiển thị *','','required maxlength="100"'),'Lưu tài liệu mẫu',async(f,form)=>{const file=form.querySelector('[name=file]').files[0];if(!['application/pdf','image/png','image/jpeg'].includes(file?.type))throw Error('Chỉ nhận PDF, PNG hoặc JPEG.');if(file.size>1024*1024)throw Error('Tệp tối đa 1 MB trong bản demo.');const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(Error('Không đọc được tệp.'));reader.readAsDataURL(file);});const doc={id:crypto.randomUUID(),name:f.name.trim(),size:file.size,type:file.type,data,visitId:p.visit.id,recorded:new Date().toISOString(),author:author()};(p.documents??=[]).push(doc);try{repo.save();}catch{p.documents.pop();throw Error('Không đủ dung lượng lưu demo. Hãy chọn tệp nhỏ hơn.');}persist('Đã lưu tài liệu mẫu trong trình duyệt.');});});
  document.querySelectorAll('[data-view-document]').forEach(b=>b.onclick=()=>{const d=selected().documents.find(d=>d.id===b.dataset.viewDocument);if(!d)return;openDialog(`<h2>${esc(d.name)}</h2><p>${esc(d.type)} · ${esc(d.visitId)}</p><div id="documentPreview"></div><div class="form-actions"><button data-cancel>Đóng</button></div>`);const bytes=Uint8Array.from(atob(d.data.split(',')[1]),c=>c.charCodeAt(0));const url=URL.createObjectURL(new Blob([bytes],{type:d.type}));const el=document.createElement(d.type==='application/pdf'?'iframe':'img');el.src=url;el.title=d.name;el.className='document-preview';document.querySelector('#documentPreview').append(el);document.querySelector('#modal').addEventListener('close',()=>URL.revokeObjectURL(url),{once:true});});
  document.querySelectorAll('[data-preview-form]').forEach(b=>b.onclick=()=>previewForm(b.dataset.previewForm));
  document.querySelector('#newTemplate')?.addEventListener('click',()=>{if(!can('forms'))return;formDialog('Tạo biểu mẫu nháp','Mỗi dòng: mã_trường | nhãn | kiểu (text/number) | đơn vị | bắt buộc (yes/no) | concept UUID (nếu có).',input('name','Tên biểu mẫu *','','required')+area('definition','Định nghĩa trường *','symptom | Triệu chứng | text | | yes |\nmeasurement | Chỉ số đo | number | | no |','required'),'Lưu bản nháp',f=>{const fields=f.definition.split('\n').filter(x=>x.trim()).map(line=>{const [key,label,type,unit,required,concept]=line.split('|').map(x=>x.trim());if(!['text','number'].includes(type))throw Error('Kiểu trường chỉ nhận text hoặc number.');return {key,label:label||'',type,unit:unit||'',required:required==='yes',concept:concept||''};});validateFormDefinition(fields);ws().forms.push({id:crypto.randomUUID(),name:f.name.trim(),version:1,kind:'custom',fields});persist('Đã lưu biểu mẫu nháp, chưa xuất bản lên backend.');});});
  document.querySelectorAll('[data-fill-form]').forEach(b=>b.onclick=()=>{const p=selected();if(!writable(p)||(!can('exam')&&!can('vitals')))return;const f=ws().forms.find(f=>f.id===b.dataset.fillForm);formDialog(f.name,p.name+' · '+p.visit.id,f.fields.map(x=>input(x.key,x.label+(x.unit?' ('+x.unit+')':'')+(x.required?' *':''),'',`type="${x.type==='number'?'number':'text'}" ${x.type==='number'?'step="any"':''} ${x.required?'required':''}`)).join(''),'Lưu bản ghi mẫu',values=>{(p.visit.formEntries??=[]).push({id:crypto.randomUUID(),formId:f.id,name:f.name,version:f.version,fields:structuredClone(f.fields),values,visitId:p.visit.id,recorded:new Date().toISOString(),author:author()});persist('Đã lưu bản ghi biểu mẫu demo.');});});
  document.querySelector('#newAccount')?.addEventListener('click',()=>{if(!can('admin'))return;formDialog('Thêm tài khoản demo','Chỉ lưu tên và vai trò để thử giao diện; không tạo tài khoản OpenMRS.',input('name','Tên hiển thị *','','required')+`<label>Vai trò<select name="role">${Object.entries(roles).map(([r,n])=>`<option value="${r}">${n}</option>`).join('')}</select></label>`,'Tạo tài khoản demo',f=>{ws().accounts.push({id:crypto.randomUUID(),name:f.name.trim(),role:f.role,active:true});persist('Đã tạo tài khoản demo.');});});
  document.querySelectorAll('[data-toggle-account]').forEach(b=>b.onclick=()=>{if(!can('admin'))return;const a=ws().accounts.find(a=>a.id===b.dataset.toggleAccount);if(a.id==='demo-admin')return;a.active=!a.active;persist('Đã cập nhật trạng thái tài khoản demo.');});
 }
 return {navigation,isPage,page,chart,bind,audit};
}
