import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
let stored=null;
globalThis.localStorage={getItem:()=>stored,setItem:(k,v)=>{stored=v;}};
const source=await readFile(new URL('./repository.js',import.meta.url),'utf8');
const {DemoRepository}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const first=new DemoRepository();
assert.equal(first.patients.length,5);
assert.equal(new Set(first.patients.map(p=>p.id)).size,5);
assert.equal(first.patients.filter(p=>p.name==='Nguyễn Minh Anh').length,2);
first.patients[0].visit.reason='Kiểm tra giữ dữ liệu';first.save();
assert.equal(new DemoRepository().patients[0].visit.reason,'Kiểm tra giữ dữ liệu');
stored='{broken';assert.equal(new DemoRepository().patients.length,5);
stored='{}';assert.equal(new DemoRepository().patients.length,5);
const html=await readFile(new URL('./index.html',import.meta.url),'utf8');
assert.match(html,/lang="vi"/);assert.match(html,/type="module"/);
console.log('PASS: dữ liệu giả, mã riêng cho người trùng tên, giữ dữ liệu và phục hồi khi dữ liệu lưu hỏng.');
const workflowSource=await readFile(new URL('./workflow.js',import.meta.url),'utf8');
const {permitted,createOrder,recordResult,validateAppointment,validateFormDefinition}=await import('data:text/javascript;base64,'+Buffer.from(workflowSource).toString('base64'));
assert.equal(permitted('reception','exam'),false);
assert.equal(permitted('doctor','orders'),true);
assert.equal(permitted('nurse','results'),true);
assert.throws(()=>createOrder({visit:{status:'closed'}},{name:'Mẫu',reason:'Test'},'Bác sĩ'));
const patient={visit:{id:'visit-test',status:'open'}};
const order=createOrder(patient,{name:'Mẫu',type:'Xét nghiệm',reason:'Test'},'Bác sĩ');
assert.equal(order.visitId,'visit-test');
assert.throws(()=>recordResult(order,{value:'1',state:'final'},'Điều dưỡng'));
recordResult(order,{value:'1',state:'final',confirmed:true,unit:'đơn vị mẫu'},'Điều dưỡng');
assert.equal(order.status,'completed');
assert.equal(order.result.unit,'đơn vị mẫu');
assert.throws(()=>recordResult({...order,status:'cancelled'},{value:'2',state:'preliminary'},'Điều dưỡng'));
const appointment={patientId:'patient-test',time:new Date(Date.now()+86400000).toISOString(),service:'Khám',provider:'Demo'};
validateAppointment([],appointment);
assert.throws(()=>validateAppointment([{...appointment,status:'scheduled'}],appointment));
assert.throws(()=>validateFormDefinition([{key:'same',label:'A'},{key:'same',label:'B'}]));
assert.throws(()=>validateFormDefinition([{key:'value',label:'A',concept:'not-a-uuid'}]));
console.log('PASS: ma trận role, lượt đã đóng, mapping chỉ định, kết quả xác nhận, chỉ định hủy, lịch hẹn trùng và concept UUID.');
const apiSource=await readFile(new URL('./api.js',import.meta.url),'utf8');
const {authenticateSession}=await import('data:text/javascript;base64,'+Buffer.from(apiSource).toString('base64'));
const login={origin:'http://127.0.0.1:8080',username:'demo',password:'not-a-real-password'};
await assert.rejects(()=>authenticateSession({...login,origin:'https://example.org'},()=>{}),/localhost/);
await assert.rejects(()=>authenticateSession(login,async()=>{throw Error('offline');}),/Không kết nối/);
await assert.rejects(()=>authenticateSession(login,async()=>new Response('{}',{status:401,headers:{'content-type':'application/json'}})),/bị từ chối/);
await assert.rejects(()=>authenticateSession(login,async()=>new Response('<html/>',{headers:{'content-type':'text/html'}})),/JSON/);
await assert.rejects(()=>authenticateSession(login,async()=>new Response('{"authenticated":false}',{headers:{'content-type':'application/json'}})),/chưa xác thực/);
const session=await authenticateSession(login,async()=>new Response('{"authenticated":true,"user":{"uuid":"demo-user","display":"Demo"}}',{headers:{'content-type':'application/json'}}));
assert.equal(session.uuid,'demo-user');
console.log('PASS: session UI adapter rejects remote origins, network failure, 401, HTML fallback and unauthenticated JSON.');
