import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
let stored=null;
globalThis.localStorage={getItem:()=>stored,setItem:(k,v)=>{stored=v;}};
const source=await readFile(new URL('./repository.js',import.meta.url),'utf8');
const {DemoRepository}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const first=new DemoRepository();
assert.equal(first.patients.length,5);
assert.equal(new Set(first.patients.map(p=>p.id)).size,5);
assert.equal(first.patients.filter(p=>p.name==='Nguyễn Minh Anh').length,2);
first.patients[0].visit.reason='Kiểm tra giữ dữ liệu';first.save();
assert.equal(new DemoRepository().patients[0].visit.reason,'Kiểm tra giữ dữ liệu');
stored='{broken';assert.equal(new DemoRepository().patients.length,5);
stored='{}';assert.equal(new DemoRepository().patients.length,5);
const html=await readFile(new URL('./index.html',import.meta.url),'utf8');
assert.match(html,/lang="vi"/);assert.match(html,/type="module"/);
console.log('PASS: dữ liệu giả, mã riêng cho người trùng tên, giữ dữ liệu và phục hồi khi dữ liệu lưu hỏng.');
const workflowSource=await readFile(new URL('./workflow.js',import.meta.url),'utf8');
const {permitted,createOrder,recordResult,validateAppointment,validateFormDefinition,ROLE_DEFINITIONS,canOpenPage,canOpenTab,canFillForm,demoAccount,accountPermitted,accountRoles,billTotal,addPayment,refundBill,workspacePermitted,cancelVisit,validateExamDraft}=await import('data:text/javascript;base64,'+Buffer.from(workflowSource).toString('base64'));
assert.equal(permitted('reception','exam'),false);
assert.equal(permitted('doctor','orders'),true);
assert.equal(permitted('nurse','results'),false);
assert.deepEqual(Object.keys(ROLE_DEFINITIONS).sort(),['admin','cashier','doctor','lab','manager','nurse','pharmacy','reception']);
for(const role of Object.keys(ROLE_DEFINITIONS))assert.equal(canOpenPage(role,'workspace'),true);
for(const action of ['register','openVisit','exam','vitals','notes','orders','documents','results','closeVisit'])assert.equal(permitted('admin',action),false);
assert.equal(permitted('doctor','vitals'),false);
assert.equal(permitted('nurse','exam'),false);
assert.equal(permitted('reception','openVisit'),true);
assert.equal(permitted('doctor','closeVisit'),true);
assert.equal(canOpenPage('admin','patients'),false);
assert.equal(canOpenPage('reception','templates'),false);
assert.equal(canOpenPage('nurse','appointments'),false);
assert.equal(canOpenPage('doctor','appointments'),true);
for(const tab of ['exam','documents','tests','allergies','notes'])assert.equal(canOpenTab('reception',tab),false);
assert.equal(canOpenTab('nurse','exam'),true); // Clinical context is read-only.
assert.equal(canOpenTab('admin','overview'),false);
assert.equal(canOpenTab('unknown','exam'),false);
for(const invalidRole of ['__proto__','toString','constructor']){assert.equal(permitted(invalidRole,'exam'),false);assert.equal(canOpenPage(invalidRole,'workspace'),false);assert.deepEqual(accountRoles({roles:[invalidRole]}),[]);}
assert.equal(canOpenPage(null,'workspace'),false);
assert.equal(canFillForm('nurse',{targetRole:'doctor'}),false);
assert.equal(canFillForm('nurse',{targetRole:'nurse'}),true);
assert.equal(canFillForm('admin',{targetRole:'doctor'}),false);
assert.equal(canFillForm('doctor',{targetRole:'doctor'}),true);
assert.equal(demoAccount([{id:'locked',role:'doctor',active:false}],'locked'),null);
assert.equal(demoAccount([{id:'bad',role:'root',active:true}],'bad'),null);
assert.equal(demoAccount(first.workspace.accounts,'demo-nurse').role,'nurse');
assert.equal(first.workspace.accounts.length,8);
assert.deepEqual(accountRoles({roles:['doctor','nurse','doctor','unknown']}),['doctor','nurse']);
assert.equal(accountPermitted({roles:['doctor','nurse'],active:true},'vitals'),true);
assert.equal(accountPermitted({roles:['doctor'],active:true},'vitals',{hasNurse:false}),true);
assert.equal(accountPermitted({roles:['doctor'],active:true},'vitals',{hasNurse:true}),false);
assert.equal(accountPermitted({roles:['doctor','nurse'],active:false},'vitals'),false);
assert.equal(permitted('lab','results'),true);
assert.equal(permitted('cashier','prices'),false);assert.equal(permitted('admin','prices'),true);
for(const role of ['cashier','lab','pharmacy','manager']){
 assert.equal(canOpenPage(role,'patients'),false);
 assert.equal(canOpenTab(role,'exam'),false);
 assert.equal(permitted(role,'exam'),false);
}
const bill={items:[{price:50000,quantity:2}],status:'unpaid',transactions:[]};
assert.equal(billTotal(bill),100000);
assert.throws(()=>addPayment(bill,{amount:100001},'Thu ngân'));
assert.throws(()=>addPayment(bill,{amount:0.5},'Thu ngân'));
addPayment(bill,{amount:40000,method:'Tiền mặt'},'Thu ngân');assert.equal(bill.status,'partial');
addPayment(bill,{amount:60000,method:'Tiền mặt'},'Thu ngân');assert.equal(bill.status,'paid');
assert.throws(()=>refundBill(bill,'','Thu ngân'));
refundBill(bill,'Hoàn tiền kiểm thử','Thu ngân');assert.equal(bill.status,'refunded');assert.equal(bill.transactions.reduce((n,t)=>n+t.amount,0),0);
assert.throws(()=>addPayment(bill,{amount:1},'Thu ngân'));
stored=JSON.stringify({patients:first.patients,workspace:{forms:[{id:'legacy',name:'Phiếu cũ',kind:'custom',fields:[]}]}});
assert.equal(new DemoRepository().workspace.forms[0].targetRole,'doctor');
assert.throws(()=>createOrder({visit:{status:'closed'}},{name:'Mẫu',reason:'Test'},'Bác sĩ'));
const patient={visit:{id:'visit-test',status:'open'}};
const order=createOrder(patient,{name:'Mẫu',type:'Xét nghiệm',reason:'Test'},'Bác sĩ');
assert.equal(order.visitId,'visit-test');
assert.throws(()=>recordResult(order,{value:'1',state:'final'},'Nguồn giả lập'));
recordResult(order,{value:'1',state:'final',confirmed:true,unit:'đơn vị mẫu'},'Nguồn giả lập');
assert.equal(order.status,'completed');
assert.throws(()=>recordResult(order,{value:'Ghi đè kết quả',state:'final',confirmed:true},'Nguồn giả lập'));
assert.throws(()=>recordResult({status:'requested'},{value:'1',state:'unknown'},'Nguồn giả lập'));
assert.equal(order.result.unit,'đơn vị mẫu');
assert.throws(()=>recordResult({...order,status:'cancelled'},{value:'2',state:'preliminary'},'Nguồn giả lập'));
const appointment={patientId:'patient-test',time:new Date(Date.now()+86400000).toISOString(),service:'Khám',provider:'Demo'};
validateAppointment([],appointment);
assert.throws(()=>validateAppointment([{...appointment,status:'scheduled'}],appointment));
assert.throws(()=>validateFormDefinition([{key:'same',label:'A'},{key:'same',label:'B'}]));
assert.throws(()=>validateFormDefinition([{key:'value',label:'A',concept:'not-a-uuid'}]));
const rollbackRepo=new DemoRepository(),savedReason=rollbackRepo.patients[0].visit.reason;
rollbackRepo.patients[0].visit.reason='Chỉnh sửa chưa lưu';
const originalSetItem=localStorage.setItem;localStorage.setItem=()=>{throw Error('Quota exceeded');};
assert.throws(()=>rollbackRepo.save());rollbackRepo.restore();assert.equal(rollbackRepo.patients[0].visit.reason,savedReason);localStorage.setItem=originalSetItem;
console.log('PASS: 8 role, privilege kiêm nhiệm, thanh toán/hoàn, phục hồi khi lưu lỗi, lượt đã đóng, mapping chỉ định, kết quả xác nhận, chỉ định hủy, lịch hẹn trùng và concept UUID.');
const apiSource=await readFile(new URL('./api.js',import.meta.url),'utf8');
const {authenticateSession}=await import('data:text/javascript;base64,'+Buffer.from(apiSource).toString('base64'));
const login={origin:'http://127.0.0.1:8080',username:'demo',password:'not-a-real-password'};
await assert.rejects(()=>authenticateSession({...login,origin:'https://example.org'},()=>{}),/localhost/);
await assert.rejects(()=>authenticateSession(login,async()=>{throw Error('offline');}),/Không kết nối/);
await assert.rejects(()=>authenticateSession(login,async()=>new Response('{}',{status:401,headers:{'content-type':'application/json'}})),/bị từ chối/);
await assert.rejects(()=>authenticateSession(login,async()=>new Response('<html/>',{headers:{'content-type':'text/html'}})),/JSON/);
await assert.rejects(()=>authenticateSession(login,async()=>new Response('{"authenticated":false}',{headers:{'content-type':'application/json'}})),/chưa xác thực/);
const session=await authenticateSession(login,async()=>new Response('{"authenticated":true,"user":{"uuid":"demo-user","display":"Demo"}}',{headers:{'content-type':'application/json'}}));
assert.equal(session.uuid,'demo-user');
console.log('PASS: session UI adapter rejects remote origins, network failure, 401, HTML fallback and unauthenticated JSON.');

// Cross-role commands stay in the workspace that owns them, even for multi-role accounts.
const combined={roles:['admin','doctor','reception','nurse'],active:true};
assert.equal(workspacePermitted(combined,'admin','exam'),false);
assert.equal(workspacePermitted(combined,'reception','exam'),false);
assert.equal(workspacePermitted(combined,'doctor','billing'),false);
assert.equal(workspacePermitted(combined,'nurse','exam'),false);
assert.equal(workspacePermitted(combined,'doctor','vitals'),true);
assert.equal(workspacePermitted({...combined,active:false},'doctor','exam'),false);
assert.equal(canOpenPage('lab','lab-results'),true);
assert.equal(canOpenPage('pharmacy','dispensed'),true);
assert.equal(canOpenPage('manager','lab-results'),false);
assert.equal(canOpenPage('admin','integration'),true);
assert.equal(canOpenPage('doctor','integration'),false);
const abandoned={visit:{id:'local-test',status:'open',orders:[{id:'original-order'}]}};
assert.throws(()=>cancelVisit(abandoned,' ','Tiếp đón'));
cancelVisit(abandoned,'Người bệnh hủy khám','Tiếp đón');
assert.equal(abandoned.visit.status,'closed');assert.equal(abandoned.visit.closure.reason,'Người bệnh hủy khám');
assert.equal(abandoned.visit.orders[0].id,'original-order');assert.throws(()=>cancelVisit(abandoned,'Ghi đè','Tiếp đón'));
const examDraft={reason:'Dữ liệu giả',history:'Dữ liệu giả',clinical:'Dữ liệu giả',diagnosis:'Dữ liệu giả',plan:'Dữ liệu giả',certainty:'provisional',medications:[{name:'Thuốc giả',directions:'Cách dùng giả',unit:'Đơn vị giả',doseUnit:'Đơn vị giả',route:'Đường dùng giả',frequency:'Tần suất giả',dose:'1',quantity:'1',durationDays:'1'}]};
validateExamDraft(examDraft);
assert.throws(()=>validateExamDraft({...examDraft,certainty:'unknown'}));
assert.throws(()=>validateExamDraft({...examDraft,medications:[{...examDraft.medications[0],quantity:'1.5'}]}));
assert.throws(()=>validateExamDraft({...examDraft,medications:[{...examDraft.medications[0],durationDays:'0'}]}));
assert.throws(()=>validateExamDraft({...examDraft,medications:[{...examDraft.medications[0],route:''}]}));

// These UUIDs are synthetic unit fixtures only; no requests are sent to an instance.
const mappingSource=await readFile(new URL('./backend-mapping.js',import.meta.url),'utf8');
const {buildVitalsCommand,VITAL_FIELD_MAP}=await import('data:text/javascript;base64,'+Buffer.from(mappingSource).toString('base64'));
const fixtureUuid=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const links=Object.fromEntries(['patientUuid','visitUuid','encounterUuid','providerUuid','locationUuid','userUuid'].map((key,i)=>[key,fixtureUuid(i+1)]));
const metadata={version:'synthetic-unit-test',concepts:Object.fromEntries(VITAL_FIELD_MAP.map((f,i)=>[f.code,fixtureUuid(i+100)]))};
const input={context:{...links,clinicalHistory:'Must not enter command'},values:{temperature:'36.7',spo2:0,weight:'',height:null},measuredAt:'2026-10-08T09:30:00+07:00',metadata};
const command=buildVitalsCommand(input);
assert.deepEqual(command.observations.map(o=>[o.fieldCode,o.value,o.unit]),[['vitals.nhiet_do',36.7,'Cel'],['vitals.spo2',0,'%']]);
assert.deepEqual(command.context,links);
assert.throws(()=>buildVitalsCommand({...input,context:{...links,patientUuid:'BN-000128'}}));
assert.throws(()=>buildVitalsCommand({...input,metadata:{...metadata,concepts:{}}}));
assert.throws(()=>buildVitalsCommand({...input,metadata:{...metadata,version:''}}));
assert.throws(()=>buildVitalsCommand({...input,values:{temperature:'36.7°C'}}));
assert.throws(()=>buildVitalsCommand({...input,values:{temperature:true}}));
assert.throws(()=>buildVitalsCommand({...input,values:{temperature:' '}}));
assert.throws(()=>buildVitalsCommand({...input,values:{}}));
assert.throws(()=>buildVitalsCommand({...input,measuredAt:'2026-10-08T09:30'}));
assert.throws(()=>buildVitalsCommand({...input,metadata:{...metadata,concepts:{...metadata.concepts,'vitals.spo2':metadata.concepts['vitals.nhiet_do']}}}));
console.log('PASS: workspace privilege boundaries, result/dispensing history routes, cancellation provenance, structured medication fields and metadata-backed vital commands.');
