import { createOperations } from './operations.js';
import { authenticateSession } from './api.js';
import { BACKEND_SERVICES, VITAL_FIELD_MAP } from './backend-mapping.js';
import { canWriteVisit, createOrder, validateAppointment, validateFormDefinition, ROLE_PERMISSIONS, ROLE_DEFINITIONS, canOpenPage, canOpenTab, canFillForm, accountRoles, medicationInstructions, validateExamDraft } from './workflow.js';

export function createModules(ctx){
 const {repo,state,esc,fmt,icon,can,selected,render,persist,toast,openDialog,localDate,roles,author,facility,navigate,openPatient,openTab}=ctx;
 const operations=createOperations(ctx);
 const ws=()=>repo.workspace;
 const allVisits=p=>[...(p.visit?[p.visit]:[]),...p.history];
 const writable=p=>canWriteVisit(p);
 const heading=(title,description,action='')=>`<div class="heading"><div><div class="eyebrow">VINSHC / KHÔNG GIAN NGHIỆP VỤ</div><h1>${title}</h1><p>${description}</p></div>${action}</div>`;
 const empty=text=>`<div class="empty">${text}</div>`;
 const btn=(id,text,enabled=true)=>`<button class="primary" id="${id}" ${!enabled?'disabled':''}>${icon('plus')}${text}</button>`;
 const options=(list,current)=>list.map(x=>`<option value="${esc(x)}" ${x===current?'selected':''}>${esc(x)}</option>`).join('');
 const requireAction=(action,p)=>{if(!can(action))throw Error('Vai trò hiện tại không có quyền thực hiện thao tác này.');if(p&&!writable(p))throw Error('Cần lượt khám đang mở để ghi nhận.');};
 const meta=v=>`<div class="record-meta">${esc(v.author||'Dữ liệu mẫu')} · ${v.recorded?fmt(v.recorded):v.created?fmt(v.created):''} · ${esc(v.visitId||'')}</div>`;
 const table=(headers,rows)=>`<div class="table-scroll"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows||`<tr><td colspan="${headers.length}">${empty('Chưa có dữ liệu trong mục này.')}</td></tr>`}</tbody></table></div>`;
 const section=(title,body,action='',subtitle='')=>`<section class="panel"><div class="panel-header"><div><h2>${title}</h2>${subtitle?`<small>${subtitle}</small>`:''}</div>${action}</div>${body}</section>`;
 const patientLink=p=>`<button class="link-button" data-patient="${esc(p.id)}">${esc(p.name)}</button><small class="record-meta">${esc(p.id)}</small>`;
 const badge=(text,c='')=>`<span class="badge ${c}">${text}</span>`;
 const formDialog=(title,description,body,submit,handler)=>{
  const accountId=state.accountId,role=state.role,patientId=state.selected,visitId=selected()?.visit?.id;
  openDialog(`<h2>${title}</h2><p>${description}</p><form id="moduleForm"><div class="form-grid">${body}</div><p class="error" id="moduleError" role="alert"></p><div class="form-actions"><button type="button" data-cancel>Hủy</button><button class="primary" type="submit">${submit}</button></div></form>`);
  document.querySelector('#moduleForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget;const button=form.querySelector('[type=submit]');button.disabled=true;try{if(accountId!==state.accountId||role!==state.role||!canOpenPage(state.role,state.page)||patientId!==state.selected||visitId!==selected()?.visit?.id)throw Error('Phiên hoặc lượt khám đã thay đổi. Hãy mở lại thao tác.');await handler(Object.fromEntries(new FormData(form)),form);document.querySelector('#modal').close();}catch(error){document.querySelector('#moduleError').textContent=error.message||'Không thể lưu.';}finally{button.disabled=false;}};
 };
 const input=(name,label,value='',extra='')=>`<label>${label}<input name="${name}" value="${esc(value)}" ${extra}></label>`;
 const area=(name,label,value='',extra='')=>`<label class="full">${label}<textarea name="${name}" ${extra}>${esc(value)}</textarea></label>`;
 const select=(name,label,choices,current)=>`<label>${label}<select name="${name}">${options(choices,current)}</select></label>`;
 const canManageAppointment=a=>can('appointments')&&(state.role==='reception'||(state.role==='doctor'&&a.providerId===state.accountId));
 const visitHint=p=>!writable(p)?'<div class="module-notice">Lượt khám đã kết thúc hoặc chưa mở. Có thể xem dữ liệu; mở lượt mới để ghi nhận.</div>':'';
 const visibleForms=()=>ws().forms.filter(f=>state.role==='admin'||f.targetRole===state.role);
 function navigation(){
  const icons={workspace:'grid',patients:'users',vitals:'heart',appointments:'clock',queue:'users',active:'file',history:'clock',templates:'file',admin:'users',settings:'grid',prices:'file',audit:'clock',connection:'shield',integration:'shield',billing:'file',receipts:'file',lab:'heart','lab-results':'check',dispensing:'file',dispensed:'check',reports:'grid'};
  return `<nav class="workspace-nav" aria-label="Các chức năng của ${roles[state.role]}">${ROLE_DEFINITIONS[state.role].pages.map(([p,n])=>`<button data-page="${p}" class="${state.page===p?'active':''}" ${state.page===p?'aria-current="page"':''}>${icon(icons[p])}<span>${n}</span></button>`).join('')}</nav>`;
 }
 function isPage(p){return ['workspace','active','queue','appointments','templates','admin','settings','audit','connection','billing','receipts','prices','lab','lab-results','dispensing','dispensed','reports','integration'].includes(p);}
 function page(){
  if(!canOpenPage(state.role,state.page))return heading('Không có quyền truy cập','Chọn chức năng phù hợp với vai trò hiện tại.');
  if(['billing','receipts','prices','lab','lab-results','dispensing','dispensed','reports'].includes(state.page))return operations.page();
  return ({workspace:roleHome,connection,appointments,active,queue,templates,admin:administration,settings,integration,audit:auditPage}[state.page]||roleHome)();
 }
 function roleHome(){
  if(['cashier','lab','pharmacy','manager'].includes(state.role))return operations.home();
  const role=state.role,r=ROLE_DEFINITIONS[role],activePatients=repo.patients.filter(writable),scheduled=ws().appointments.filter(a=>a.status==='scheduled');
  const pendingVitals=activePatients.filter(p=>!p.visit.vitals),ready=activePatients.filter(p=>p.visit.vitals&&!p.visit.exam),examining=activePatients.filter(p=>p.visit.exam);
  const finished=repo.patients.filter(p=>p.visit?.status==='closed'&&p.visit.closure?.kind!=='cancelled');
  const metrics={
   reception:[[repo.patients.length,'Hồ sơ tiếp nhận','Tìm theo mã, họ tên hoặc SĐT'],[repo.patients.filter(p=>!p.visit||p.visit.status==='closed').length,'Sẵn sàng tiếp nhận','Hồ sơ chưa có lượt đang mở'],[activePatients.length,'Lượt đang mở','Theo dõi tiến trình tiếp nhận'],[scheduled.length,'Lịch hẹn chờ đến','Chưa xác nhận đã tiếp nhận']],
   nurse:[[pendingVitals.length,'Chờ ghi sinh hiệu','Ưu tiên danh sách chưa đo'],[activePatients.filter(p=>p.visit.vitals).length,'Đã ghi sinh hiệu','Có thể xem và cập nhật lượt mở'],[activePatients.reduce((n,p)=>n+(p.visit.notes||[]).filter(v=>v.role==='nurse'||v.type.includes('điều dưỡng')).length,0),'Ghi chú điều dưỡng','Theo từng lượt chăm sóc'],[activePatients.length,'Lượt cần theo dõi','Bàn giao thông tin cho bác sĩ']],
   doctor:[[ready.length,'Chờ bác sĩ','Có sinh hiệu, chưa có phiếu khám'],[examining.length,'Đang hoàn thiện','Đã lưu phiếu, lượt còn mở'],[activePatients.reduce((n,p)=>n+(p.visit.orders||[]).filter(o=>o.status==='requested'||o.status==='in-progress').length,0),'Chỉ định chờ kết quả','Theo dõi từ dữ liệu nguồn'],[finished.length,'Lượt đã hoàn tất','Xem lại hồ sơ chỉ đọc']],
   admin:[[ws().accounts.filter(a=>a.active).length,'Tài khoản hoạt động','Theo vai trò đã phân công'],[ws().accounts.filter(a=>!a.active).length,'Tài khoản đã khóa','Không được chọn vào phiên demo'],[ws().forms.length,'Định nghĩa biểu mẫu','Phân công bác sĩ / điều dưỡng'],[ws().forms.filter(f=>f.kind==='custom').length,'Biểu mẫu nháp','Cần duyệt trước khi xuất bản']],
  }[role];
  const actions={reception:[['patients','Tiếp nhận người bệnh','users'],['appointments','Tạo & xem lịch hẹn','clock'],['queue','Điều phối hàng đợi','grid']],nurse:[['vitals','Danh sách đo sinh hiệu','heart'],['patients','Hồ sơ chăm sóc','file'],['templates','Biểu mẫu điều dưỡng','grid']],doctor:[['active','Mở danh sách khám','users'],['history','Tra cứu lịch sử','clock'],['templates','Biểu mẫu khám','file']],admin:[['admin','Quản lý tài khoản','users'],['templates','Thiết kế biểu mẫu','file'],['connection','Kiểm tra kết nối','shield']]}[role];
  const steps={reception:[['Đối chiếu hồ sơ','Họ tên, ngày sinh và mã hồ sơ.'],['Mở lượt khám','Ghi lý do đến khám, giữ nguyên định danh.'],['Điều phối','Chuyển người bệnh tới khu đo sinh hiệu.']],nurse:[['Xác nhận người bệnh','Đối chiếu định danh và lượt đang mở.'],['Ghi sinh hiệu','Chỉ số, đơn vị, thời điểm đo và người ghi.'],['Bàn giao chăm sóc','Ghi chú điều dưỡng để bác sĩ tiếp tục khám.']],doctor:[['Xem thông tin trước khám','Sinh hiệu, dị ứng và lịch sử liên quan.'],['Khám & ghi nhận','Bệnh sử, chẩn đoán, thuốc và chỉ định.'],['Hoàn tất lượt khám','Lưu phiếu khám trước khi kết thúc.']],admin:[['Quản lý tài khoản','Thêm, phân vai trò, khóa và mở khóa.'],['Quản lý cấu hình','Cơ sở, biểu mẫu và mapping metadata.'],['Kiểm tra vận hành','Nhật ký và khả năng kết nối backend.']]}[role];
  const side=`<aside><section class="panel role-guide"><span class="eyebrow">NHIỆM VỤ TRONG CA</span><h2>${roles[role]}</h2>${steps.map(([title,description],i)=>`<div class="step"><div class="step-number">${i+1}</div><div><strong>${title}</strong><p>${description}</p></div></div>`).join('')}</section><div class="side-tip"><h3>${icon('shield')}${role==='admin'?'Quyền theo nhiệm vụ':'Đối chiếu trước khi ghi'}</h3><p>${role==='admin'?'Quản trị hệ thống không tự có quyền xem hoặc sửa hồ sơ lâm sàng.':'Giữ đúng người bệnh và lượt khám trong mỗi lần ghi nhận.'}</p></div></aside>`;
  let tasks;
  if(role==='admin')tasks=section('Công việc quản trị',`<div class="admin-tasks">${[['admin','Tài khoản & phân quyền','Tài khoản riêng cho từng nhân viên; theo dõi trạng thái khóa.','users'],['templates','Biểu mẫu theo vai trò','Định nghĩa trường, đơn vị, concept UUID và đối tượng sử dụng.','file'],['settings','Cấu hình cơ sở','Tên cơ sở trình diễn và các dữ liệu cần chốt với backend.','grid'],['audit','Nhật ký thao tác','Đối chiếu tài khoản, thời điểm và thao tác đã thực hiện.','clock']].map(([page,title,description,i])=>`<button data-page="${page}">${icon(i)}<span><strong>${title}</strong><small>${description}</small></span>${icon('arrow')}</button>`).join('')}</div>`,'','Cấu hình trong bản trình diễn chưa được nạp lên OpenMRS.');
  else{
   const list=role==='reception'?repo.patients.filter(p=>!writable(p)):role==='nurse'?[...pendingVitals,...activePatients.filter(p=>p.visit.vitals)]:[...ready,...activePatients.filter(p=>!p.visit.vitals),...examining];
   tasks=section({reception:'Danh sách tiếp nhận',nurse:'Danh sách chăm sóc',doctor:'Danh sách khám'}[role],table(['NGƯỜI BỆNH / MÃ HỒ SƠ','TRẠNG THÁI','THAO TÁC'],list.map(p=>`<tr><td>${patientLink(p)}<small class="record-meta">${esc(p.gender)} · ${esc(p.dob.split('-').reverse().join('/'))}</small></td><td>${badge(!writable(p)?'Chưa có lượt đang mở':p.visit.exam?'Đã lưu phiếu khám':p.visit.vitals?'Đã có sinh hiệu':'Chờ ghi sinh hiệu',!p.visit?.vitals?'wait':'')}</td><td><button class="link-button" data-patient="${p.id}" data-target-tab="${r.defaultTab}">${role==='reception'?'Tiếp nhận':role==='nurse'?'Ghi / xem sinh hiệu':'Vào khám'} ${icon('arrow')}</button></td></tr>`).join('')),role==='reception'?btn('register','Đăng ký hồ sơ mới'):'',role==='nurse'?'Người bệnh chưa có sinh hiệu được xếp trước.':role==='doctor'?'Ưu tiên lượt đã có sinh hiệu; có thể mở lượt khác khi cần.':'Chọn hồ sơ, đối chiếu thông tin rồi mở lượt khám.');
  }
  return `<section class="role-welcome role-${role}"><div><span class="eyebrow">${roles[role].toLocaleUpperCase('vi')} / PHÒNG KHÁM NGOẠI TRÚ</span><h1>${r.title}</h1><p>${r.description}</p><small>${esc(facility())} · ${new Intl.DateTimeFormat('vi-VN',{weekday:'long',day:'numeric',month:'long',timeZone:'Asia/Ho_Chi_Minh'}).format(new Date())}</small></div><div class="role-emblem">${icon({reception:'users',nurse:'heart',doctor:'file',admin:'shield'}[role])}</div></section><div class="role-actions">${actions.map(([page,label,i])=>`<button data-page="${page}">${icon(i)}${label}${icon('arrow')}</button>`).join('')}</div><div class="stats role-stats">${metrics.map(([count,label,hint],i)=>`<div class="stat"><div><small>${label}</small><strong>${String(count).padStart(2,'0')}</strong><span>${hint}</span></div><div class="iconbox">${icon(['users','clock','heart','check'][i])}</div></div>`).join('')}</div><div class="role-workspace">${tasks}${side}</div>`;
 }
 function settings(){const config=ws().facility;return heading('Cấu hình cơ sở','Thông tin dùng trên bản in mẫu và biến thể quy trình tại phòng khám.')+`<div class="workspace"><section class="panel form-card"><h3>Thông tin cơ sở</h3><form id="facilityForm"><div class="form-grid">${input('name','Tên cơ sở *',facility(),'maxlength="100" required')}${input('address','Địa chỉ cơ sở',config.address,'maxlength="250"')}${input('license','Số giấy phép hoạt động',config.license,'maxlength="100"')}<label>Thời điểm thu phí<select name="paymentTiming"><option value="before" ${config.paymentTiming==='before'?'selected':''}>Trước khi khám</option><option value="after" ${config.paymentTiming==='after'?'selected':''}>Sau khi khám</option></select></label><label>Nguồn cận lâm sàng<select name="clsMode"><option value="onsite" ${config.clsMode==='onsite'?'selected':''}>Thực hiện tại cơ sở</option><option value="external" ${config.clsMode==='external'?'selected':''}>Gửi ngoài / báo cáo đính kèm</option></select></label><label class="checkbox-label"><input type="checkbox" name="hasNurse" ${config.hasNurse?'checked':''}>Có điều dưỡng ghi sinh hiệu</label><label class="checkbox-label"><input type="checkbox" name="hasPharmacy" ${config.hasPharmacy?'checked':''}>Có quầy thuốc tại cơ sở</label></div><p class="readonly">Khi không có điều dưỡng, bác sĩ được ghi sinh hiệu trong cấu hình demo. Khi tắt quầy thuốc, chức năng ghi cấp thuốc tại cơ sở dừng hoạt động.</p><p class="readonly">Thời gian hiển thị: Asia/Ho_Chi_Minh · Ngôn ngữ: Tiếng Việt. Trả trước/trả sau hiển thị hướng dẫn thu; chưa tự chặn luồng khám theo trạng thái thanh toán.</p><div class="form-actions"><button class="primary">Lưu cấu hình demo</button></div></form></section><aside class="panel side-section"><h3>Metadata cần xác nhận</h3><p class="readonly">Location UUID, visit/encounter type, concept sinh hiệu, danh mục thuốc, order type và privilege cần thống nhất với backend.</p><p class="readonly">Mẫu in còn cần thông tin người hành nghề và đối chiếu nội dung bắt buộc. Cấu hình này không thay đổi OpenMRS.</p></aside></div>`;}
 function integration(){
  return heading('Bàn giao FE–BE','Đối chiếu hợp đồng dữ liệu, module và phụ thuộc trước khi nối API thật.')+`<div class="module-notice">Workspace đang dùng dữ liệu giả. Bảng này mô tả phần cần bàn giao; trạng thái không được suy ra từ việc module đã cài hoặc kiểm tra session thành công.</div>`+section('Dịch vụ nghiệp vụ',table(['DỊCH VỤ FE','BACKEND / MODULE','DỮ LIỆU','MỐC / TRẠNG THÁI'],BACKEND_SERVICES.map(s=>`<tr><td>${esc(s.name)}</td><td class="wrap-cell">${esc(s.module)}</td><td class="wrap-cell">${esc(s.scope)}</td><td>${esc(s.milestone)}<small class="record-meta">${esc(s.status)}</small></td></tr>`).join('')))+`<div class="section-gap"></div>`+section('Mapping sinh hiệu',table(['TRƯỜNG','MÃ DỮ LIỆU','ĐƠN VỊ TRAO ĐỔI','CONCEPT UUID'],VITAL_FIELD_MAP.map(f=>`<tr><td>${f.label}</td><td>${f.code}</td><td>${f.unit}</td><td>Chờ DATA-02 bàn giao</td></tr>`).join('')),'','Nguồn: docs/FRONTEND.md và docs/DATA_DICTIONARY.md. Không tạo UUID tạm để gửi backend.');
 }
 function auditPage(){return heading('Nhật ký thao tác','Đối chiếu tài khoản, thời điểm và nội dung thao tác trong bản demo.')+section('Nhật ký giao diện',table(['THỜI ĐIỂM','NGƯỜI THỰC HIỆN','THAO TÁC'],ws().audit.slice(0,50).map(a=>`<tr><td>${fmt(a.time)}</td><td>${esc(a.actor)}<small class="record-meta">${esc(a.accountId||'Dữ liệu phiên cũ')}</small></td><td class="wrap-cell">${esc(a.action)}</td></tr>`).join('')),'','Lưu trên trình duyệt; chưa phải nhật ký kiểm toán backend.');}
 function connection(){return heading('Đăng nhập OpenMRS','Kiểm tra phiên backend; không chuyển dữ liệu demo thành hồ sơ thật.')+`<div class="workspace"><section class="panel form-card"><h3>Phiên làm việc tại cơ sở</h3><p class="readonly">Nhập tài khoản của instance local. Thông tin đăng nhập chỉ dùng cho một request, không lưu trong trình duyệt.</p><form id="apiSessionForm"><div class="form-grid">${input('origin','Địa chỉ gateway local *','http://127.0.0.1:8080','type="url" required')}${input('username','Tên đăng nhập *','','required autocomplete="username"')}${input('password','Mật khẩu *','','type="password" required autocomplete="current-password"')}<label>Cơ sở demo<input value="VinSHC Development Clinic" disabled></label></div><p id="apiSessionStatus" role="status" class="readonly"></p><div class="form-actions"><button class="primary" type="submit">Kiểm tra đăng nhập</button></div></form></section><aside class="panel side-section"><h3>Hai nguồn dữ liệu riêng biệt</h3><p class="readonly">Các màn hình phòng khám hiện dùng dữ liệu giả. Đăng nhập thành công ở đây chỉ xác nhận phiên API local, chưa đọc/ghi hồ sơ backend.</p><p class="readonly">Quyền và location thực tế phải lấy từ OpenMRS khi triển khai adapter. Cần gateway cho phép origin của frontend hoặc reverse proxy cùng origin.</p></aside></div>`;}
 function active(){const patients=repo.patients.filter(p=>writable(p));return heading('Lượt khám đang hoạt động','Theo dõi lượt đang mở theo cơ sở và thời điểm tiếp nhận.')+section('Danh sách lượt khám',table(['BỆNH NHÂN','LƯỢT KHÁM','TIẾP NHẬN','SINH HIỆU','PHIẾU KHÁM',''],patients.map(p=>`<tr><td>${patientLink(p)}</td><td>${esc(p.visit.id)}</td><td>${fmt(p.visit.started)}</td><td>${badge(p.visit.vitals?'Đã ghi':'Chưa ghi',p.visit.vitals?'':'wait')}</td><td>${badge(p.visit.exam?'Đã ghi':'Chưa ghi',p.visit.exam?'':'wait')}</td><td><button data-patient="${p.id}" class="link-button">Mở lượt →</button></td></tr>`).join('')));}
 function queue(){const patients=repo.patients.filter(p=>writable(p)).sort((a,b)=>new Date(a.visit.started)-new Date(b.visit.started));const rooms=['Tiếp nhận','Đo sinh hiệu','Phòng khám 01'];return heading('Hàng đợi khám','Theo dõi tiến trình tại phòng khám; thứ tự tiếp nhận không thay thế phân loại cấp cứu.')+`<div class="queue-summary">${rooms.map((r,i)=>`<div><span>BƯỚC ${i+1}</span><strong>${r}</strong><small>Phân công và trạng thái trong dữ liệu demo</small></div>`).join('')}</div>`+section('Hàng đợi đang hoạt động',table(['THỨ TỰ','BỆNH NHÂN','KHU VỰC','TRẠNG THÁI','THAO TÁC'],patients.map((p,i)=>{const q=p.visit.queue||{};return `<tr><td><span class="queue-number">${String(i+1).padStart(2,'0')}</span></td><td>${patientLink(p)}</td><td>${esc(q.room||(p.visit.vitals?'Phòng khám 01':'Đo sinh hiệu'))}<small class="record-meta">${esc(ws().accounts.find(a=>a.id===q.providerId)?.name||'Chưa phân bác sĩ')}</small></td><td>${badge(q.state||'Chờ đến lượt',q.state==='Đang phục vụ'?'exam':'wait')}</td><td>${can('queue')?`<button data-queue="${p.id}" class="link-button">Điều phối</button>`:`<button data-patient="${p.id}" class="link-button">Mở hồ sơ</button>`}</td></tr>`;}).join('')),'','Queue · Chưa kết nối module backend');}
 function appointments(){return heading('Lịch hẹn','Quản lý lịch theo bệnh nhân, dịch vụ và người khám.',can('appointments')?btn('newAppointment','Tạo lịch hẹn'):'')+section('Lịch hẹn phòng khám',table(['BỆNH NHÂN','THỜI GIAN','DỊCH VỤ / NGƯỜI KHÁM','TRẠNG THÁI',''],[...ws().appointments].sort((a,b)=>new Date(a.time)-new Date(b.time)).map(a=>{const p=repo.patients.find(p=>p.id===a.patientId);return `<tr><td>${p?patientLink(p):esc(a.patientId)}</td><td>${fmt(a.time)}</td><td>${esc(a.service)}<small class="record-meta">${esc(a.provider)}</small></td><td>${badge({scheduled:'Đã đặt',arrived:'Đã tiếp nhận',cancelled:'Đã hủy'}[a.status],a.status==='cancelled'?'neutral':'')}</td><td>${canManageAppointment(a)&&a.status==='scheduled'?`<button data-arrived="${a.id}" class="link-button">Đã đến</button><button data-cancel-appointment="${a.id}" class="link-button danger">Hủy hẹn</button>`:''}</td></tr>`;}).join('')),'','Lịch hẹn không tự mở lượt khám; cần đối chiếu bệnh nhân khi tiếp nhận.');}
 function templates(){return heading('Thư viện biểu mẫu','Biểu mẫu tiếng Việt theo lượt khám; quản lý định nghĩa và tham chiếu concept.',can('forms')?btn('newTemplate','Tạo biểu mẫu nháp'):'')+`<div class="template-grid">${visibleForms().map(f=>`<section class="panel template-card"><div class="template-icon">${icon('file')}</div><span class="article-kicker">${f.kind==='builtin'?'BIỂU MẪU GIAO DIỆN':'BẢN NHÁP TÙY CHỈNH'}</span><h2>${esc(f.name)}</h2><p>${roles[f.targetRole]} · Phiên bản ${f.version} · ${f.kind==='builtin'?'Cấu trúc khám/sinh hiệu hiện có':`${f.fields.length} trường`}</p><small>Chưa xuất bản lên O3 Forms / Initializer</small><button data-preview-form="${f.id}" class="link-button">Xem cấu trúc →</button></section>`).join('')}</div><div class="module-notice">Form builder hiện tạo bản nháp và xem trước. UUID, phiên bản schema O3 và mapping metadata cần được người 1/3/4 xác nhận trước khi nạp backend.</div>`;}
 function administration(){if(!can('admin'))return heading('Không có quyền truy cập','Chỉ quản trị được xem màn hình này.');return heading('Tài khoản & quyền','Tài khoản riêng theo nhiệm vụ; khóa tài khoản sẽ loại khỏi danh sách chọn phiên.',btn('newAccount','Thêm tài khoản demo'))+section('Nhân viên tại cơ sở',table(['TÀI KHOẢN','VAI TRÒ','TRẠNG THÁI','THAO TÁC'],ws().accounts.map(a=>`<tr><td>${esc(a.name)}<small class="record-meta">${esc(a.id)}</small></td><td>${accountRoles(a).map(r=>roles[r]).join(' · ')||'Không hợp lệ'}</td><td>${badge(a.active?'Đang hoạt động':'Đã khóa',a.active?'':'neutral')}</td><td>${a.id!=='demo-admin'&&a.id!==state.accountId?`<button class="link-button" data-edit-account="${a.id}">Phân vai trò</button><button class="link-button" data-toggle-account="${a.id}">${a.active?'Khóa':'Mở khóa'}</button>`:'Quản trị phiên hiện tại / dự phòng'}</td></tr>`).join('')))+`<div style="height:20px"></div>`+section('Ma trận thao tác frontend',table(['VAI TRÒ','ĐƯỢC THỰC HIỆN'],Object.entries(ROLE_PERMISSIONS).map(([r,actions])=>`<tr><td>${roles[r]}</td><td class="wrap-cell">${actions.map(a=>({register:'Đăng ký hồ sơ',updatePatient:'Sửa hành chính',openVisit:'Mở lượt',cancelVisit:'Kết thúc tiếp nhận có lý do',appointments:'Lịch hẹn',queue:'Điều phối',vitals:'Sinh hiệu',exam:'Khám / chẩn đoán / thuốc / dị ứng',notes:r==='nurse'?'Ghi chú điều dưỡng':'Ghi chú lâm sàng',orders:'Chỉ định',documents:'Tài liệu',closeVisit:'Kết thúc lượt',fillNurseForm:'Phiếu điều dưỡng',fillDoctorForm:'Phiếu bác sĩ',admin:'Tài khoản',forms:'Định nghĩa biểu mẫu',configuration:'Cấu hình cơ sở',connection:'Kiểm tra kết nối',audit:'Nhật ký',results:'Kết quả được giao',billing:'Thu / hoàn / hủy phí',prices:'Bảng giá',receipts:'Phiếu thu',dispense:'Cấp theo đơn',reports:'Báo cáo tổng hợp',prescriptions:'Xác nhận đơn mẫu'}[a])).join(' · ')}</td></tr>`).join('')),'','Ma trận FE đề xuất theo kế hoạch; cần thực thi lại bằng privilege trên backend.');}
 function chart(p){if(!canOpenTab(state.role,state.tab))return empty('Vai trò hiện tại không có quyền xem nội dung này.');const method={conditions,allergies,meds,notes,orders,tests,documents,forms:patientForms}[state.tab];return method?method(p):empty('Chọn một mục hồ sơ.');}
 function conditions(p){const rows=allVisits(p).filter(v=>v.exam?.diagnosis).map(v=>`<tr><td>${esc(v.exam.diagnosis)}</td><td>${esc(v.exam.icd||'Chưa mã hóa')}</td><td>${fmt(v.exam.recorded||v.started)}</td><td>${esc(v.id)}</td><td>${badge(v.status==='closed'?'Lượt đã đóng':'Lượt đang mở',v.status==='closed'?'neutral':'')}</td></tr>`).join('');return section('Chẩn đoán theo lượt khám',table(['CHẨN ĐOÁN','ICD-10','GHI NHẬN','LƯỢT KHÁM','TRẠNG THÁI'],rows),can('exam')&&writable(p)?'<button class="primary" data-tab-target="exam">Ghi trong phiếu khám</button>':'','Mã do bác sĩ nhập; chưa đối chiếu danh mục Việt Nam.');}
 function allergies(p){const a=p.visit?.allergyAssessment||p.visit?.exam;const current=a?.state||a?.allergyState||p.allergy;return visitHint(p)+section('Dị ứng & phản ứng bất lợi',`<div class="form-card"><div class="allergy-status">${icon('shield')}<div><strong>${esc(current||'Chưa khai thác')}</strong><p>${esc(a?.detail||a?.allergyDetail||'Chưa ghi nhận chi tiết tác nhân và phản ứng.')}</p></div></div>${a?meta(a):''}<p class="readonly">“Chưa khai thác” khác với “đã khai thác và không ghi nhận”. Cần xác nhận với người bệnh trong lượt hiện tại.</p></div>`,can('exam')&&writable(p)?btn('editAllergy','Cập nhật dị ứng'):'');}
 function meds(p){return section('Thuốc đã ghi nhận',table(['THUỐC / HÀM LƯỢNG','CÁCH DÙNG','SỐ LƯỢNG','LƯỢT / THỜI ĐIỂM'],allVisits(p).flatMap(v=>(v.exam?.medications||[]).map(m=>`<tr><td>${esc(m.name)}</td><td class="wrap-cell pre-wrap">${esc(medicationInstructions(m))}</td><td>${esc(m.quantity)} ${esc(m.unit)}</td><td>${esc(v.id)}<small class="record-meta">${fmt(v.exam.recorded||v.started)}</small></td></tr>`)).join('')),can('prescriptions')?`<div class="form-shortcuts">${writable(p)?'<button data-tab-target="exam">Ghi đơn trong phiếu khám</button>':''}${writable(p)&&p.visit.exam?.medications?.length?'<button class="primary" id="confirmPrescription">Xác nhận đơn mẫu</button>':''}${p.visit?.prescriptions?.length?'<button id="printPrescription">Xem / in đơn mẫu</button>':''}</div>`:'','Danh sách thuốc theo đơn mẫu; không suy ra người bệnh đang sử dụng hoặc đã được cấp phát.');}
 function notes(p){const list=allVisits(p).flatMap(v=>(v.notes||[]).map(n=>({...n,visitId:v.id})));return visitHint(p)+section('Ghi chú chăm sóc',list.length?`<div class="records-list">${list.reverse().map(n=>`<article class="record-card"><span class="pill">${esc(n.type)}</span><p class="pre-wrap">${esc(n.content)}</p>${meta(n)}</article>`).join('')}</div>`:empty('Chưa có ghi chú chăm sóc.'),can('notes')&&writable(p)?btn('newNote','Thêm ghi chú'):'');}
 function orders(p){const list=allVisits(p).flatMap(v=>v.orders||[]);return visitHint(p)+section('Chỉ định dịch vụ',table(['DỊCH VỤ','LÝ DO','ƯU TIÊN','TRẠNG THÁI',''],list.map(o=>`<tr><td>${esc(o.name)}<small class="record-meta">${esc(o.type)} · ${esc(o.visitId)}</small></td><td class="wrap-cell">${esc(o.reason)}</td><td>${esc(o.priority)}</td><td>${badge({requested:'Đã chỉ định','in-progress':'Đang thực hiện',completed:'Đã có kết quả',cancelled:'Đã hủy'}[o.status],o.status==='requested'?'wait':'')}</td><td>${can('orders')&&writable(p)&&o.visitId===p.visit.id&&o.status==='requested'?`<button class="link-button danger" data-cancel-order="${o.id}">Hủy</button>`:''}</td></tr>`).join('')),can('orders')&&writable(p)?`<div class="form-shortcuts">${btn('newOrder','Tạo chỉ định')}<button id="printOrders">Xem / in chỉ định</button></div>`:'','Chỉ định mẫu; chưa gửi LIS, PACS hoặc hệ thống xét nghiệm.');}
 function tests(p){const list=allVisits(p).flatMap(v=>v.orders||[]).filter(o=>o.status!=='cancelled');return section('Kết quả xét nghiệm / báo cáo',list.length?`<div class="records-list">${list.map(o=>`<article class="record-card"><div class="record-title"><div><h3>${esc(o.name)}</h3><small>${esc(o.visitId)}</small></div>${badge(o.result?(o.result.state==='final'?'Hoàn tất từ nguồn':'Sơ bộ'):'Chưa có kết quả',o.result?'':'wait')}</div>${o.result?`<p class="pre-wrap">${esc(o.result.value)} ${esc(o.result.unit)}</p><p class="readonly">Khoảng tham chiếu từ nguồn: ${esc(o.result.reference||'Chưa cung cấp')}</p>${meta(o.result)}${o.result.attachment?`<button class="link-button" data-result-attachment="${o.id}">Xem báo cáo đính kèm: ${esc(o.result.attachment.name)}</button>`:''}`:'<p class="readonly">Chưa nhận được dữ liệu nguồn cho chỉ định này.</p>'}</article>`).join('')}</div>`:empty('Chưa có chỉ định hoặc kết quả trong hồ sơ.'),'','Chỉ đọc dữ liệu nguồn. KTV nhập và xác nhận trong danh sách được giao. API kết quả thực tế còn chờ backend bàn giao.');}
 function documents(p){const docs=p.documents||[];return section('Tài liệu & tệp đính kèm',table(['TÀI LIỆU','LOẠI / DUNG LƯỢNG','NGUỒN / NGƯỜI GHI',''],docs.map(d=>`<tr><td>${esc(d.name)}<small class="record-meta">${esc(d.visitId)}</small></td><td>${esc(d.type)} · ${(d.size/1024).toFixed(0)} KB</td><td>${esc(d.author)}<small class="record-meta">${fmt(d.recorded)}</small></td><td><button data-view-document="${d.id}" class="link-button">Xem</button></td></tr>`).join('')),can('documents')&&writable(p)?btn('uploadDocument','Thêm tài liệu mẫu'):'','PDF / PNG / JPEG, tối đa 1 MB mỗi tệp. Chỉ tải tài liệu giả, lưu trong trình duyệt demo.');}
 function patientForms(p){return visitHint(p)+section('Biểu mẫu của lượt khám',`<div class="form-card"><div class="form-shortcuts">${state.role==='nurse'?'<button data-tab-target="vitals">Phiếu sinh hiệu →</button>':'<button data-tab-target="exam">Phiếu khám ngoại trú →</button>'}</div>${visibleForms().filter(f=>f.kind==='custom').map(f=>`<div class="custom-form-item"><div><strong>${esc(f.name)}</strong><small>${roles[f.targetRole]} · Phiên bản ${f.version} · ${f.fields.length} trường</small></div><button data-fill-form="${f.id}" ${!writable(p)||!canFillForm(state.role,f)?'disabled':''}>Điền bản mẫu</button></div>`).join('')}<h3 style="margin-top:25px">Bản ghi biểu mẫu tùy chỉnh</h3>${allVisits(p).flatMap(v=>(v.formEntries||[]).map(entry=>`<article class="record-card"><strong>${esc(entry.name)} · v${entry.version}</strong>${entry.fields.map(f=>`<p>${esc(f.label)}: ${esc(entry.values[f.key]??'Chưa ghi nhận')} ${esc(f.unit||'')}</p>`).join('')}${meta(entry)}</article>`)).join('')||'<p class="readonly">Chưa có bản ghi biểu mẫu tùy chỉnh.</p>'}</div>`);}
 function audit(action){ws().audit.unshift({time:new Date().toISOString(),actor:author(),accountId:state.accountId,role:state.role,action});ws().audit=ws().audit.slice(0,150);}
 function previewForm(id){const f=ws().forms.find(f=>f.id===id);if(!f||!visibleForms().some(form=>form.id===id))return;openDialog(`<h2>${esc(f.name)}</h2><p>${roles[f.targetRole]} · Phiên bản ${f.version} · Chưa xuất bản lên backend</p>${f.kind==='builtin'?`<p class="readonly">${f.id==='form-vitals'?'Huyết áp, mạch, nhiệt độ, nhịp thở, SpO₂, cân nặng, chiều cao, thời điểm đo.':'Lý do khám, bệnh sử, tiền sử, khám lâm sàng, dị ứng, chẩn đoán/ICD-10/mức chắc chắn, kế hoạch/tái khám và thuốc có liều/đơn vị/đường dùng/tần suất/số ngày.'}</p>`:table(['TRƯỜNG','KIỂU','ĐƠN VỊ','CONCEPT UUID'],f.fields.map(v=>`<tr><td>${esc(v.label)}${v.required?' *':''}<small class="record-meta">${esc(v.key)}</small></td><td>${esc(v.type)}</td><td>${esc(v.unit||'—')}</td><td class="wrap-cell">${esc(v.concept||'Chưa mapping')}</td></tr>`).join(''))}<div class="form-actions"><button data-cancel>Đóng</button></div>`);}
 function bind(){
  operations.bind();
  document.querySelector('#apiSessionForm')?.addEventListener('submit',async e=>{
   e.preventDefault();if(!can('connection'))return;const form=e.currentTarget,button=form.querySelector('[type=submit]'),status=document.querySelector('#apiSessionStatus');
   button.disabled=true;status.className='readonly';status.textContent='Đang xác thực phiên OpenMRS…';
   try{const result=await authenticateSession(Object.fromEntries(new FormData(form)));status.textContent='API đã xác thực tài khoản '+result.display+'. Các màn hình lâm sàng vẫn dùng dữ liệu demo.';}catch(error){status.className='error';status.textContent=error.message;}finally{form.querySelector('[name=password]').value='';button.disabled=false;}
  });
  document.querySelectorAll('[data-patient]').forEach(b=>b.onclick=()=>openPatient(b.dataset.patient,b.dataset.targetTab));
  document.querySelectorAll('[data-tab-target]').forEach(b=>b.onclick=()=>openTab(b.dataset.tabTarget));
  document.querySelectorAll('[data-queue]').forEach(b=>b.onclick=()=>{if(!can('queue'))return;const p=repo.patients.find(p=>p.id===b.dataset.queue);formDialog('Điều phối lượt khám',p.name+' · '+p.visit.id,select('room','Khu vực',['Tiếp nhận','Đo sinh hiệu','Phòng khám 01'],p.visit.queue?.room)+`<label>Bác sĩ tiếp nhận<select name="providerId"><option value="">Chưa phân công</option>${ws().accounts.filter(a=>a.active&&accountRoles(a).includes('doctor')).map(a=>`<option value="${a.id}" ${a.id===p.visit.queue?.providerId?'selected':''}>${esc(a.name)}</option>`).join('')}</select></label>`+select('state','Trạng thái',['Chờ đến lượt','Đang phục vụ','Tạm vắng'],p.visit.queue?.state),'Lưu điều phối',f=>{requireAction('queue',p);p.visit.queue=f;persist('Đã cập nhật hàng đợi mẫu.');});});
  document.querySelector('#newAppointment')?.addEventListener('click',()=>{if(!can('appointments'))return;const choices=repo.patients.map(p=>`<option value="${p.id}">${esc(p.name)} · ${p.id}</option>`).join('');formDialog('Tạo lịch hẹn','Lịch mẫu; không gửi thông báo hoặc tự mở lượt khám.',`<label>Bệnh nhân *<select name="patientId">${choices}</select></label>`+input('time','Thời gian hẹn *',localDate(new Date(Date.now()+86400000)),`type="datetime-local" required`)+select('service','Dịch vụ',['Khám ngoại trú','Tái khám','Khám sức khỏe'])+`<label>Người khám *<select name="providerId">${ws().accounts.filter(a=>a.active&&accountRoles(a).includes('doctor')&&(state.role==='reception'||a.id===state.accountId)).map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join('')}</select></label>`+area('reason','Ghi chú'),'Lưu lịch hẹn',f=>{requireAction('appointments');const provider=ws().accounts.find(a=>a.id===f.providerId&&a.active&&accountRoles(a).includes('doctor'));if(!provider||(state.role==='doctor'&&provider.id!==state.accountId))throw Error('Người khám không hợp lệ với phiên hiện tại.');f.provider=provider.name;f.time=new Date(f.time).toISOString();validateAppointment(ws().appointments,f);ws().appointments.push({...f,id:crypto.randomUUID(),status:'scheduled'});persist('Đã tạo lịch hẹn mẫu.');});});
  document.querySelectorAll('[data-arrived],[data-cancel-appointment]').forEach(b=>b.onclick=()=>{if(!can('appointments'))return;const a=ws().appointments.find(a=>a.id===(b.dataset.arrived||b.dataset.cancelAppointment));if(!a||!canManageAppointment(a)||a.status!=='scheduled')return;if(b.dataset.arrived){a.status='arrived';persist('Đã đánh dấu người bệnh đến. Mở hồ sơ để tiếp nhận.');}else{openDialog('<h2>Hủy lịch hẹn?</h2><p>Lịch được giữ lại với trạng thái đã hủy.</p><div class="form-actions"><button data-cancel>Quay lại</button><button id="confirmAppointment">Hủy lịch</button></div>');document.querySelector('#confirmAppointment').onclick=()=>{if(!canManageAppointment(a)||a.status!=='scheduled')return;a.status='cancelled';document.querySelector('#modal').close();persist('Đã hủy lịch hẹn mẫu.');};}});
  document.querySelector('#editAllergy')?.addEventListener('click',()=>{const p=selected();if(!can('exam')||!writable(p))return;const a=p.visit.allergyAssessment||{};formDialog('Xác nhận tình trạng dị ứng',p.name+' · '+p.visit.id,select('state','Tình trạng',['Chưa khai thác','Không rõ thông tin dị ứng','Không ghi nhận dị ứng sau khai thác','Có dị ứng'],a.state)+area('detail','Tác nhân / phản ứng',a.detail),'Lưu dị ứng',f=>{requireAction('exam',p);if(f.state==='Có dị ứng'&&!f.detail.trim())throw Error('Cần ghi tác nhân hoặc phản ứng dị ứng.');p.visit.allergyAssessment={...f,recorded:new Date().toISOString(),author:author()};p.allergy=f.state==='Có dị ứng'?f.detail:f.state;if(p.visit.exam){p.visit.exam.allergyState=f.state;p.visit.exam.allergyDetail=f.detail;}persist('Đã ghi nhận trạng thái dị ứng trong lượt khám.');});});
  document.querySelector('#newNote')?.addEventListener('click',()=>{const p=selected();if(!can('notes')||!writable(p))return;formDialog('Ghi chú chăm sóc',p.name+' · '+p.visit.id,select('type','Loại ghi chú',ROLE_DEFINITIONS[state.role].noteTypes)+area('content','Nội dung *','','required'),'Lưu ghi chú',f=>{requireAction('notes',p);if(!ROLE_DEFINITIONS[state.role].noteTypes.includes(f.type))throw Error('Loại ghi chú không phù hợp với vai trò.');if(!f.content.trim())throw Error('Cần nội dung ghi chú.');(p.visit.notes??=[]).push({...f,role:state.role,recorded:new Date().toISOString(),author:author()});persist('Đã lưu ghi chú theo lượt khám.');});});
  document.querySelector('#printPrescription')?.addEventListener('click',()=>{if(!can('prescriptions'))return;const p=selected(),rx=p.visit?.prescriptions?.at(-1);if(!rx)return;operations.printDocument('ĐƠN THUỐC MẪU',p,`<p>${esc(rx.id)} · ${esc(p.visit.id)}</p>${p.visit.closure?.kind==='cancelled'?'<p class="error">Lượt đã hủy / bỏ về. Đơn chỉ đọc, không được ghi cấp thuốc.</p>':''}${table(['THUỐC / HÀM LƯỢNG','CÁCH DÙNG','SL'],rx.medications.map(m=>`<tr><td>${esc(m.name)}</td><td class="wrap-cell pre-wrap">${esc(medicationInstructions(m))}</td><td>${esc(m.quantity)} ${esc(m.unit)}</td></tr>`).join(''))}<p>Người kê: ${esc(rx.author)} · Giấy phép: ${esc(rx.license||'Chưa cấu hình')}</p><p>Dặn dò: ${esc(rx.plan||'Chưa ghi lời dặn trong bản đơn đã xác nhận')}</p>`);});
  document.querySelector('#printOrders')?.addEventListener('click',()=>{if(!can('orders'))return;const p=selected();operations.printDocument('PHIẾU CHỈ ĐỊNH MẪU',p,`<p>${esc(p.visit?.id||'')}</p>${table(['DỊCH VỤ','LÝ DO','ƯU TIÊN'],(p.visit?.orders||[]).filter(o=>o.status!=='cancelled').map(o=>`<tr><td>${esc(o.name)}</td><td class="wrap-cell">${esc(o.reason)}</td><td>${esc(o.priority)}</td></tr>`).join(''))}`);});
  document.querySelector('#confirmPrescription')?.addEventListener('click',()=>{
   const p=selected();if(!can('prescriptions')||!writable(p)||!p.visit.exam?.medications?.length)return;
   const exam=p.visit.exam;if(p.visit.prescriptions?.some(rx=>rx.examRecorded===exam.recorded)){toast('Phiếu khám này đã có đơn mẫu được xác nhận.');return;}
   formDialog('Xác nhận đơn mẫu',p.name+' · '+p.visit.id,'<label class="full checkbox-label"><input name="confirmed" type="checkbox" required>Đã đối chiếu thuốc, cách dùng, số lượng và người bệnh (demo).</label>','Xác nhận đơn',f=>{requireAction('prescriptions',p);if(f.confirmed!=='on'||p.visit.exam!==exam)throw Error('Phiếu khám đã thay đổi hoặc chưa xác nhận.');validateExamDraft(exam);const rx={id:'DT-'+crypto.randomUUID().slice(0,8).toUpperCase(),examRecorded:exam.recorded,medications:structuredClone(exam.medications),plan:exam.plan,diagnosis:exam.diagnosis,icd:exam.icd,certainty:exam.certainty,created:new Date().toISOString(),author:author(),prescriberId:state.accountId,license:ctx.session()?.license||'',status:'ready'};(p.visit.prescriptions??=[]).push(rx);persist('Đã xác nhận đơn mẫu để quầy thuốc đối chiếu.');});
  });
  document.querySelector('#newOrder')?.addEventListener('click',()=>{const p=selected();if(!can('orders')||!writable(p))return;formDialog('Tạo chỉ định dịch vụ',p.name+' · '+p.visit.id,select('type','Nhóm dịch vụ',['Xét nghiệm','Chẩn đoán hình ảnh','Dịch vụ khác'])+`<label>Giao thực hiện<select name="assignedTo"><option value="">Gửi ngoài / chưa phân công</option>${ws().accounts.filter(a=>a.active&&accountRoles(a).includes('lab')).map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join('')}</select></label>`+input('name','Tên dịch vụ *','','required maxlength="150"')+select('priority','Mức ưu tiên',['Thường','Ưu tiên'])+area('reason','Lý do chỉ định *','','required'),'Lưu chỉ định',f=>{requireAction('orders',p);if(f.assignedTo&&!ws().accounts.some(a=>a.id===f.assignedTo&&a.active&&accountRoles(a).includes('lab')))throw Error('Người thực hiện không hợp lệ.');const order=createOrder(p,f,author());order.assignedTo=f.assignedTo;persist('Đã tạo chỉ định mẫu. Chưa gửi tới LIS / PACS.');});});
  document.querySelectorAll('[data-cancel-order]').forEach(b=>b.onclick=()=>{const p=selected(),o=p.visit.orders.find(o=>o.id===b.dataset.cancelOrder);if(!can('orders')||!writable(p)||o.status!=='requested')return;formDialog('Hủy chỉ định','Giữ chỉ định và lý do hủy trong lịch sử.',area('reason','Lý do hủy *','','required'),'Xác nhận hủy',f=>{requireAction('orders',p);if(o.status!=='requested')throw Error('Chỉ định đã thay đổi trạng thái.');if(!f.reason.trim())throw Error('Cần lý do hủy.');o.status='cancelled';o.cancelReason=f.reason;o.cancelled=new Date().toISOString();persist('Đã hủy chỉ định mẫu.');});});
  document.querySelectorAll('[data-result-attachment]').forEach(b=>b.onclick=()=>{if(!canOpenTab(state.role,'tests'))return;const o=allVisits(selected()).flatMap(v=>v.orders||[]).find(o=>o.id===b.dataset.resultAttachment);if(o?.result?.attachment)operations.viewAttachment(o.result.attachment);});
  document.querySelector('#uploadDocument')?.addEventListener('click',()=>{const p=selected();if(!can('documents')||!writable(p))return;formDialog('Thêm tài liệu mẫu',p.name+' · '+p.visit.id,input('file','Tệp PDF / PNG / JPEG *','',`type="file" accept="application/pdf,image/png,image/jpeg" required`)+input('name','Tên hiển thị *','','required maxlength="100"'),'Lưu tài liệu mẫu',async(f,form)=>{requireAction('documents',p);const file=form.querySelector('[name=file]').files[0];if(!['application/pdf','image/png','image/jpeg'].includes(file?.type))throw Error('Chỉ nhận PDF, PNG hoặc JPEG.');if(file.size>1024*1024)throw Error('Tệp tối đa 1 MB trong bản demo.');const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(Error('Không đọc được tệp.'));reader.readAsDataURL(file);});requireAction('documents',p);const doc={id:crypto.randomUUID(),name:f.name.trim(),size:file.size,type:file.type,data,visitId:p.visit.id,recorded:new Date().toISOString(),author:author()};(p.documents??=[]).push(doc);persist('Đã lưu tài liệu mẫu trong trình duyệt.');});});
  document.querySelectorAll('[data-view-document]').forEach(b=>b.onclick=()=>{if(!canOpenTab(state.role,'documents'))return;const d=selected().documents.find(d=>d.id===b.dataset.viewDocument);if(!d)return;openDialog(`<h2>${esc(d.name)}</h2><p>${esc(d.type)} · ${esc(d.visitId)}</p><div id="documentPreview"></div><div class="form-actions"><button data-cancel>Đóng</button></div>`);const bytes=Uint8Array.from(atob(d.data.split(',')[1]),c=>c.charCodeAt(0));const url=URL.createObjectURL(new Blob([bytes],{type:d.type}));const el=document.createElement(d.type==='application/pdf'?'iframe':'img');el.src=url;el.title=d.name;el.className='document-preview';document.querySelector('#documentPreview').append(el);document.querySelector('#modal').addEventListener('close',()=>URL.revokeObjectURL(url),{once:true});});
  document.querySelectorAll('[data-preview-form]').forEach(b=>b.onclick=()=>previewForm(b.dataset.previewForm));
  document.querySelector('#newTemplate')?.addEventListener('click',()=>{if(!can('forms'))return;formDialog('Tạo biểu mẫu nháp','Mỗi dòng: mã_trường | nhãn | kiểu (text/number) | đơn vị | bắt buộc (yes/no) | concept UUID (nếu có).',input('name','Tên biểu mẫu *','','required')+`<label>Người điền biểu mẫu *<select name="targetRole"><option value="doctor">Bác sĩ</option><option value="nurse">Điều dưỡng</option></select></label>`+area('definition','Định nghĩa trường *','symptom | Triệu chứng | text | | yes |\nmeasurement | Chỉ số đo | number | | no |','required'),'Lưu bản nháp',f=>{requireAction('forms');if(!['doctor','nurse'].includes(f.targetRole))throw Error('Chọn bác sĩ hoặc điều dưỡng cho biểu mẫu.');const fields=f.definition.split('\n').filter(x=>x.trim()).map(line=>{const [key,label,type,unit,required,concept]=line.split('|').map(x=>x.trim());if(!['text','number'].includes(type))throw Error('Kiểu trường chỉ nhận text hoặc number.');return {key,label:label||'',type,unit:unit||'',required:required==='yes',concept:concept||''};});validateFormDefinition(fields);ws().forms.push({id:crypto.randomUUID(),name:f.name.trim(),version:1,kind:'custom',targetRole:f.targetRole,fields});persist('Đã lưu biểu mẫu nháp, chưa xuất bản lên backend.');});});
  document.querySelectorAll('[data-fill-form]').forEach(b=>b.onclick=()=>{const p=selected();const f=ws().forms.find(f=>f.id===b.dataset.fillForm);if(!writable(p)||!canFillForm(state.role,f)||!can(state.role==='nurse'?'fillNurseForm':'fillDoctorForm'))return;formDialog(f.name,p.name+' · '+p.visit.id,f.fields.map(x=>input(x.key,x.label+(x.unit?' ('+x.unit+')':'')+(x.required?' *':''),'',`type="${x.type==='number'?'number':'text'}" ${x.type==='number'?'step="any"':''} ${x.required?'required':''}`)).join(''),'Lưu bản ghi mẫu',values=>{requireAction(state.role==='nurse'?'fillNurseForm':'fillDoctorForm',p);if(!canFillForm(state.role,f))throw Error('Biểu mẫu thuộc vai trò khác.');(p.visit.formEntries??=[]).push({id:crypto.randomUUID(),formId:f.id,name:f.name,targetRole:f.targetRole,version:f.version,fields:structuredClone(f.fields),values,visitId:p.visit.id,recorded:new Date().toISOString(),author:author()});persist('Đã lưu bản ghi biểu mẫu demo.');});});
  document.querySelector('#facilityForm')?.addEventListener('submit',e=>{e.preventDefault();if(!can('configuration'))return;const f=Object.fromEntries(new FormData(e.target)),name=f.name.trim();if(!name){toast('Cần nhập tên cơ sở.');return;}Object.assign(ws().facility,{name,address:f.address.trim(),license:f.license.trim(),paymentTiming:f.paymentTiming,clsMode:f.clsMode,hasNurse:f.hasNurse==='on',hasPharmacy:f.hasPharmacy==='on'});persist('Đã lưu tên cơ sở trình diễn.');});
  const accountFields=a=>input('name','Tên hiển thị *',a?.name||'','required maxlength="100"')+input('license','Giấy phép hành nghề (nếu có)',a?.license||'','maxlength="100"')+`<fieldset class="full account-roles"><legend>Vai trò kiêm nhiệm — chọn ít nhất một</legend>${Object.entries(roles).map(([r,n])=>`<label class="checkbox-label"><input type="checkbox" name="roles" value="${r}" ${accountRoles(a).includes(r)?'checked':''}>${n}</label>`).join('')}</fieldset>`;
  const saveAccount=(values,form,account)=>{requireAction('admin');const assignedRoles=new FormData(form).getAll('roles').filter(r=>Object.hasOwn(roles,r));if(!assignedRoles.length||!values.name.trim())throw Error('Cần tên và ít nhất một vai trò.');Object.assign(account,{name:values.name.trim(),license:values.license.trim(),roles:assignedRoles,role:assignedRoles[0]});};
  document.querySelectorAll('[data-edit-account]').forEach(b=>b.onclick=()=>{
   if(!can('admin'))return;const a=ws().accounts.find(a=>a.id===b.dataset.editAccount);if(!a||a.id==='demo-admin'||a.id===state.accountId)return;
   formDialog('Phân vai trò tài khoản',a.name+' · '+a.id,accountFields(a),'Lưu phân công',(values,form)=>{saveAccount(values,form,a);persist('Đã phân vai trò kiêm nhiệm cho tài khoản demo.');});
  });
  document.querySelector('#newAccount')?.addEventListener('click',()=>{if(!can('admin'))return;formDialog('Thêm tài khoản demo','Một nhân viên có thể được giao nhiều vai trò. Không tạo tài khoản OpenMRS.',accountFields(null),'Tạo tài khoản demo',(values,form)=>{const account={id:crypto.randomUUID(),active:true};saveAccount(values,form,account);ws().accounts.push(account);persist('Đã tạo tài khoản demo.');});});
  document.querySelectorAll('[data-toggle-account]').forEach(b=>b.onclick=()=>{if(!can('admin'))return;const a=ws().accounts.find(a=>a.id===b.dataset.toggleAccount);if(!a||a.id==='demo-admin'||a.id===state.accountId)return;a.active=!a.active;persist('Đã cập nhật trạng thái tài khoản demo.');});
 }
 return {navigation,isPage,page,chart,bind,audit,printDocument:operations.printDocument};
}
