import { recordResult, billTotal, addPayment, refundBill, accountRoles, medicationInstructions } from './workflow.js';

/** Scoped operational views. They deliberately receive no full-chart navigation. */
export function createOperations(ctx){
 const {repo,state,esc,fmt,icon,can,persist,toast,openDialog,author,facility,session,localDate}=ctx;
 const ws=()=>repo.workspace;
 const money=n=>new Intl.NumberFormat('vi-VN',{style:'currency',currency:'VND',maximumFractionDigits:0}).format(n);
 const visits=()=>repo.patients.flatMap(p=>[...(p.visit?[p.visit]:[]),...p.history].map(v=>({p,v})));
 const assignedOrders=()=>visits().flatMap(({p,v})=>(v.orders||[]).filter(o=>o.assignedTo===state.accountId&&o.status!=='cancelled').map(o=>({p,v,o})));
 const dispensable=({v,rx})=>rx.status==='ready'&&v.closure?.kind!=='cancelled';
 const prescriptions=()=>visits().flatMap(({p,v})=>(v.prescriptions||[]).map(rx=>({p,v,rx})));
 const identity=p=>`<strong>${esc(p.name)}</strong><small class="record-meta">${esc(p.id)} · ${esc(p.dob?.split('-').reverse().join('/'))}</small>`;
 const heading=(title,description,action='')=>`<div class="heading"><div><span class="eyebrow">VINSHC / ${esc(state.role==='lab'?'CẬN LÂM SÀNG':'VẬN HÀNH PHÒNG KHÁM')}</span><h1>${title}</h1><p>${description}</p></div>${action}</div>`;
 const table=(heads,rows)=>`<div class="table-scroll"><table><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows||`<tr><td colspan="${heads.length}"><div class="empty">Chưa có dữ liệu phù hợp.</div></td></tr>`}</tbody></table></div>`;
 const section=(title,body,subtitle='')=>`<section class="panel"><div class="panel-header"><div><h2>${title}</h2><small>${subtitle}</small></div></div>${body}</section>`;
 const input=(name,label,value='',attrs='')=>`<label>${label}<input name="${name}" value="${esc(value)}" ${attrs}></label>`;
 const area=(name,label,value='')=>`<label class="full">${label}<textarea name="${name}" required>${esc(value)}</textarea></label>`;
 const sumPaid=b=>(b.transactions||[]).reduce((n,t)=>n+t.amount,0);
 const billLabels={unpaid:'Chưa thu',partial:'Thu một phần',paid:'Đã thu',cancelled:'Đã hủy',refunded:'Đã hoàn'};
 function form(title,description,body,action,handler){
  const accountId=state.accountId,role=state.role;
  openDialog(`<h2>${title}</h2><p>${description}</p><form id="operationForm"><div class="form-grid">${body}</div><p class="error" id="operationError" role="alert"></p><div class="form-actions"><button type="button" data-cancel>Hủy</button><button class="primary" type="submit">Lưu bản demo</button></div></form>`);
  const guard=()=>{if(state.accountId!==accountId||state.role!==role||!can(action))throw Error('Phiên hiện tại không có quyền thực hiện thao tác này.');};
  document.querySelector('#operationForm').onsubmit=async e=>{
   e.preventDefault();const f=e.currentTarget,button=f.querySelector('[type=submit]');button.disabled=true;
   try{guard();await handler(Object.fromEntries(new FormData(f)),f,guard);document.querySelector('#modal').close();}
   catch(error){document.querySelector('#operationError').textContent=error.message;}
   finally{button.disabled=false;}
  };
 }
 function printDocument(title,patient,body){
  const config=ws().facility;
  openDialog(`<article id="printBody"><div class="print-facility"><strong>${esc(facility())}</strong><p>${esc(config.address||'Địa chỉ cơ sở: chưa cấu hình')}</p><p>Giấy phép hoạt động: ${esc(config.license||'chưa cấu hình')}</p></div><h2>${title}</h2><p class="print-demo">BẢN TRÌNH DIỄN — DỮ LIỆU GIẢ</p>${patient?`<p>Người bệnh: <strong>${esc(patient.name)}</strong> · ${esc(patient.id)}<br>Ngày sinh: ${esc(patient.dob?.split('-').reverse().join('/'))}</p>`:''}${body}<p class="record-meta">In lúc ${fmt(new Date())} · ${esc(author())}</p></article><div class="form-actions"><button data-cancel>Đóng</button><button class="primary" id="printDocument">In bản mẫu</button></div>`);
  document.querySelector('#printDocument').onclick=()=>window.print();
 }
 function viewAttachment(attachment){
  if(!['application/pdf','image/png','image/jpeg'].includes(attachment?.type)||!attachment.data?.startsWith('data:')){toast('Không đọc được báo cáo đính kèm.');return;}
  try{
   const bytes=Uint8Array.from(atob(attachment.data.split(',')[1]),c=>c.charCodeAt(0)),url=URL.createObjectURL(new Blob([bytes],{type:attachment.type}));
   openDialog(`<h2>${esc(attachment.name)}</h2><p>Báo cáo mẫu đính kèm chỉ định</p><div id="resultPreview"></div><div class="form-actions"><button data-cancel>Đóng</button></div>`);
   const element=document.createElement(attachment.type==='application/pdf'?'iframe':'img');element.src=url;element.title=attachment.name;element.className='document-preview';document.querySelector('#resultPreview').append(element);
   document.querySelector('#modal').addEventListener('close',()=>URL.revokeObjectURL(url),{once:true});
  }catch{toast('Tệp báo cáo không hợp lệ hoặc không đọc được.');}
 }
 function taskPreview(){
  if(state.role==='cashier')return section('Phiếu đang chờ thu',table(['NGƯỜI BỆNH','PHIẾU PHÍ','CÒN PHẢI THU',''],ws().bills.filter(b=>['unpaid','partial'].includes(b.status)).slice(0,5).map(b=>`<tr><td>${identity(repo.patients.find(p=>p.id===b.patientId))}</td><td>${esc(b.id)}</td><td>${money(billTotal(b)-sumPaid(b))}</td><td><button class="link-button" data-pay-bill="${b.id}">Thu tiền</button></td></tr>`).join(''))+`<div class="form-card"><button class="primary" id="newBill">+ Lập phiếu phí</button></div>`);
  if(state.role==='lab')return section('Chỉ định cần thực hiện',table(['NGƯỜI BỆNH','DỊCH VỤ / LƯỢT',''],assignedOrders().filter(({v,o})=>v.status!=='closed'&&o.result?.state!=='final').slice(0,5).map(({p,v,o})=>`<tr><td>${identity(p)}</td><td>${esc(o.name)}<small class="record-meta">${esc(v.id)}</small></td><td><button class="link-button" data-lab-result="${o.id}">Ghi kết quả</button></td></tr>`).join('')),'Chỉ hiển thị công việc được giao cho tài khoản hiện tại.');
  if(state.role==='pharmacy')return section('Đơn thuốc cần đối chiếu',table(['NGƯỜI BỆNH','ĐƠN THUỐC',''],prescriptions().filter(dispensable).slice(0,5).map(({p,rx})=>`<tr><td>${identity(p)}</td><td>${esc(rx.id)}<small class="record-meta">${rx.medications.length} dòng thuốc</small></td><td>${can('dispense')?`<button class="link-button" data-dispense="${rx.id}">Đối chiếu & cấp</button>`:`<button class="link-button" data-view-rx="${rx.id}">Xem đơn</button>`}</td></tr>`).join('')),ws().facility.hasPharmacy?'Đơn đã được bác sĩ xác nhận.':'Cơ sở đang tắt quầy thuốc.');
  const rows=Array.from({length:7},(_,i)=>{const date=new Date();date.setDate(date.getDate()-i);const day=localDate(date).slice(0,10),d=reportData(day);return `<tr><td>${day.split('-').reverse().join('/')}</td><td>${d.opened}</td><td>${d.finished}</td><td>${money(d.income-d.refund)}</td></tr>`;}).join('');
  return section('Hoạt động 7 ngày gần nhất',table(['NGÀY','LƯỢT MỞ','ĐÃ KẾT THÚC','THU RÒNG'],rows),'Số liệu tổng hợp; không hiển thị danh tính người bệnh.');
 }
 function metrics(){
  const bills=ws().bills,active=visits().filter(({v})=>v.status!=='closed');
  return {cashier:[[bills.filter(b=>['unpaid','partial'].includes(b.status)).length,'Phiếu còn phải thu'],[bills.filter(b=>b.status==='paid').length,'Phiếu đã thu đủ'],[money(bills.reduce((n,b)=>n+sumPaid(b),0)),'Thu ròng trong demo'],[bills.filter(b=>['refunded','cancelled'].includes(b.status)).length,'Phiếu hoàn / hủy']],lab:[[assignedOrders().filter(({o})=>!o.result).length,'Chỉ định chờ thực hiện'],[assignedOrders().filter(({o})=>o.result?.state==='preliminary').length,'Kết quả sơ bộ'],[assignedOrders().filter(({o})=>o.result?.state==='final').length,'Kết quả hoàn tất'],[assignedOrders().length,'Chỉ định được giao']],pharmacy:[[prescriptions().filter(dispensable).length,'Đơn chờ cấp'],[prescriptions().filter(({rx})=>rx.status==='dispensed').length,'Đơn đã cấp'],[prescriptions().reduce((n,{rx})=>n+rx.medications.length,0),'Dòng thuốc theo đơn'],[ws().facility.hasPharmacy?'Đang bật':'Đang tắt','Quầy thuốc tại cơ sở']],manager:[[active.length,'Lượt đang hoạt động'],[visits().filter(({v})=>v.status==='closed'&&v.closure?.kind!=='cancelled').length,'Lượt đã hoàn tất'],[money(bills.reduce((n,b)=>n+sumPaid(b),0)),'Doanh thu ròng demo'],[ws().accounts.filter(a=>a.active&&accountRoles(a).includes('doctor')).length,'Bác sĩ hoạt động']]}[state.role];
 }
 function home(){
  const definitions={cashier:['Thu ngân','Theo dõi phí dịch vụ và tiền đã thu, giữ đầy đủ lịch sử hoàn / hủy.','billing','Mở danh sách thu phí'],lab:['Cận lâm sàng','Chỉ xem chỉ định được giao và thông tin cần thiết để đối chiếu người bệnh.','lab','Mở chỉ định được giao'],pharmacy:['Quầy thuốc','Đối chiếu đơn mẫu đã được bác sĩ xác nhận trước khi cấp thuốc.','dispensing','Mở danh sách đơn thuốc'],manager:['Hoạt động phòng khám','Theo dõi hoạt động và doanh thu ở mức tổng hợp theo ngày.','reports','Xem báo cáo ngày']};
  const [title,description,page,label]=definitions[state.role];
  return `<section class="role-welcome role-${state.role}"><div><span class="eyebrow">VẬN HÀNH / ${esc(facility())}</span><h1>${title}</h1><p>${description}</p><small>Thông tin theo nhiệm vụ · Bản trình diễn dữ liệu giả</small></div><div class="role-emblem">${icon(state.role==='lab'?'heart':'grid')}</div></section><div class="role-actions single-action"><button data-page="${page}">${icon('arrow')}${label}</button></div><div class="stats role-stats">${metrics().map(([count,title])=>`<div class="stat"><div><small>${title}</small><strong class="metric-value">${esc(count)}</strong></div></div>`).join('')}</div><div class="role-workspace">${taskPreview()}<aside><section class="panel role-guide"><span class="eyebrow">NHIỆM VỤ TRONG CA</span><h2>${{cashier:'Thu ngân',lab:'KTV cận lâm sàng',pharmacy:'Quầy thuốc',manager:'Quản lý'}[state.role]}</h2><p class="readonly">${description}</p><p class="readonly">${{cashier:'Đối chiếu định danh, dịch vụ và số tiền. Thu / hoàn / hủy đều giữ lịch sử giao dịch.',lab:'Đối chiếu mã người bệnh, chỉ định và lượt khám. Kết quả hoàn tất được giữ ở chế độ chỉ đọc.',pharmacy:'Chỉ cấp theo đơn đã xác nhận. Giữ nguyên thuốc, cách dùng và số lượng bác sĩ đã ghi.',manager:'Theo dõi lượt và doanh thu theo ngày. Số lượt trên bác sĩ là trung bình, chưa phải công suất tối đa.'}[state.role]}</p></section><div class="side-tip"><h3>${icon('shield')}Phạm vi theo nhiệm vụ</h3><p>${{cashier:'Chỉ xem dữ liệu hành chính và phiếu phí.',lab:'Chỉ xem chỉ định được giao, không mở toàn bộ bệnh án.',pharmacy:'Chỉ xem dữ liệu cần đối chiếu và đơn thuốc.',manager:'Chỉ xem tổng hợp. Chuyển sang không gian bác sĩ nếu được giao role khám.'}[state.role]}</p></div></aside></div>`;
 }
 function billing(){return heading('Thu phí dịch vụ','Đối chiếu người bệnh, lượt khám và số tiền trước khi thu.',can('billing')?'<button class="primary" id="newBill">+ Lập phiếu phí</button>':'')+section('Danh sách phiếu phí',table(['NGƯỜI BỆNH','LƯỢT / PHIẾU','TỔNG PHÍ','ĐÃ THU','TRẠNG THÁI','THAO TÁC'],ws().bills.map(b=>{const p=repo.patients.find(p=>p.id===b.patientId);return `<tr><td>${p?identity(p):esc(b.patientId)}</td><td>${esc(b.visitId)}<small class="record-meta">${esc(b.id)}</small></td><td>${money(billTotal(b))}</td><td>${money(sumPaid(b))}</td><td><span class="badge">${billLabels[b.status]}</span></td><td>${['unpaid','partial'].includes(b.status)?`<button data-pay-bill="${b.id}" class="link-button">Thu tiền</button>`:''}${b.status==='unpaid'?`<button data-cancel-bill="${b.id}" class="link-button danger">Hủy phí</button>`:''}${['paid','partial'].includes(b.status)?`<button data-refund-bill="${b.id}" class="link-button danger">Hoàn tiền</button>`:''}<button data-print-bill="${b.id}" class="link-button">Xem / in</button></td></tr>`;}).join('')),`Cấu hình thu ${ws().facility.paymentTiming==='before'?'trước':'sau'} · Các phiếu demo chưa liên kết cổng thanh toán.`);}
 function receipts(){return heading('Phiếu thu & đối chiếu','Tiền thu và tiền hoàn được giữ thành từng giao dịch.')+section('Lịch sử giao dịch',table(['THỜI ĐIỂM','PHIẾU PHÍ','SỐ TIỀN','PHƯƠNG THỨC / LÝ DO','NGƯỜI THỰC HIỆN'],ws().bills.flatMap(b=>(b.transactions||[]).map(t=>`<tr><td>${fmt(t.created)}</td><td><button class="link-button" data-print-bill="${b.id}">${esc(b.id)}</button></td><td>${money(t.amount)}</td><td>${esc(t.method)}<small class="record-meta">${esc(t.reason||'')}</small></td><td>${esc(t.author)}</td></tr>`)).join('')));}
 function prices(){return heading('Bảng giá tại cơ sở','Giá mẫu theo dịch vụ, đơn vị VND; thay đổi chỉ áp dụng cho phiếu mới.',can('prices')?'<button class="primary" id="newService">+ Thêm dịch vụ mẫu</button>':'')+section('Danh mục dịch vụ',table(['MÃ DỊCH VỤ','TÊN DỊCH VỤ','ĐƠN GIÁ'],ws().services.map(s=>`<tr><td>${esc(s.id)}</td><td>${esc(s.name)}</td><td>${money(s.price)}</td></tr>`).join('')),'Chưa dùng danh mục kỹ thuật hoặc bảng giá đã nghiệm thu.');}
 function lab(){const complete=state.page==='lab-results';return heading(complete?'Kết quả đã hoàn tất':'Chỉ định chờ xử lý','Đối chiếu mã bệnh nhân, ngày sinh, mã lượt và dịch vụ trước khi ghi kết quả.')+section('Danh sách cận lâm sàng',table(['NGƯỜI BỆNH','CHỈ ĐỊNH / LƯỢT','ƯU TIÊN','KẾT QUẢ','THAO TÁC'],assignedOrders().filter(({o})=>complete?o.result?.state==='final':o.result?.state!=='final').map(({p,v,o})=>`<tr><td>${identity(p)}</td><td>${esc(o.name)}<small class="record-meta">${esc(o.id)} · ${esc(v.id)}</small></td><td>${esc(o.priority)}</td><td><span class="badge">${o.result?.state==='final'?'Đã hoàn tất':o.result?'Sơ bộ':'Chưa có kết quả'}</span></td><td>${can('results')&&v.status!=='closed'&&o.result?.state!=='final'?`<button class="link-button" data-lab-result="${o.id}">Ghi kết quả</button>`:''}${o.result?`<button class="link-button" data-print-result="${o.id}">Xem / in báo cáo</button>`:''}</td></tr>`).join('')),'Kết quả đã hoàn tất chỉ đọc. Chỉnh sửa sau xác nhận cần quy trình đính chính riêng.');}
 function dispensing(){const complete=state.page==='dispensed';return heading(complete?'Lịch sử cấp thuốc':'Đơn chờ cấp thuốc','Chỉ hiển thị đơn mẫu được bác sĩ xác nhận; lưu nguyên bản đơn khi cấp.')+(!ws().facility.hasPharmacy?'<div class="module-notice">Cơ sở tắt quầy thuốc. Người bệnh sử dụng đơn in; không ghi cấp thuốc tại cơ sở.</div>':'')+section('Đơn thuốc theo lượt',table(['NGƯỜI BỆNH','MÃ ĐƠN / LƯỢT','NGƯỜI KÊ','TRẠNG THÁI','THAO TÁC'],prescriptions().filter(({rx})=>complete?rx.status==='dispensed':rx.status==='ready').map(({p,v,rx})=>`<tr><td>${identity(p)}</td><td>${esc(rx.id)}<small class="record-meta">${esc(v.id)} · ${rx.medications.length} dòng thuốc</small></td><td>${esc(rx.author)}<small class="record-meta">${fmt(complete?rx.dispensing?.created||rx.created:rx.created)}</small></td><td><span class="badge">${rx.status==='dispensed'?'Đã cấp':v.closure?.kind==='cancelled'?'Lượt hủy — cần đối chiếu':'Chờ cấp'}</span></td><td>${can('dispense')&&dispensable({v,rx})?`<button class="link-button" data-dispense="${rx.id}">Đối chiếu & cấp</button>`:''}<button class="link-button" data-view-rx="${rx.id}">Xem đơn</button></td></tr>`).join('')),'Cấp thuốc là prototype tùy chọn. Chưa quản lý kho, lô, hạn dùng hoặc thuốc kiểm soát đặc biệt.');}
 function reportData(day){
  const onDay=time=>localDate(time).slice(0,10)===day;
  const dayVisits=visits().filter(({v})=>onDay(v.started)),transactions=ws().bills.flatMap(b=>b.transactions||[]).filter(t=>onDay(t.created));
  return {opened:dayVisits.length,finished:dayVisits.filter(({v})=>v.status==='closed'&&v.closure?.kind!=='cancelled').length,cancelled:dayVisits.filter(({v})=>v.closure?.kind==='cancelled').length,exam:dayVisits.filter(({v})=>v.exam).length,vitals:dayVisits.filter(({v})=>v.vitals).length,income:transactions.filter(t=>t.amount>0).reduce((n,t)=>n+t.amount,0),refund:transactions.filter(t=>t.amount<0).reduce((n,t)=>n-t.amount,0),providers:ws().accounts.filter(a=>a.active&&accountRoles(a).includes('doctor')).length};
 }
 function reports(){const day=state.reportDate||localDate().slice(0,10),d=reportData(day);return heading('Báo cáo hoạt động ngày','Số liệu tổng hợp theo thời điểm mở lượt và phát sinh giao dịch.')+`<section class="panel form-card"><div class="report-controls"><label>Ngày báo cáo<input id="reportDate" type="date" value="${day}"></label><button id="printReport">Xem / in báo cáo</button></div></section><div style="height:20px"></div>`+section('Hoạt động phòng khám',table(['CHỈ SỐ','GIÁ TRỊ'],[['Lượt mở trong ngày',d.opened],['Đã ghi sinh hiệu',d.vitals],['Đã ghi phiếu khám',d.exam],['Lượt khám hoàn tất',d.finished],['Hủy / bỏ về',d.cancelled],['Bác sĩ đang hoạt động',d.providers],['Lượt / bác sĩ (trung bình)',d.providers?(d.opened/d.providers).toFixed(1):'Chưa có bác sĩ'],['Tổng thu',money(d.income)],['Tổng hoàn',money(d.refund)],['Thu ròng',money(d.income-d.refund)]].map(([label,value])=>`<tr><td>${label}</td><td>${value}</td></tr>`).join('')),'Không suy ra công suất tối đa khi chưa có lịch ca và thời lượng khám.');}
 function page(){return ({billing,receipts,prices,lab,'lab-results':lab,dispensing,dispensed:dispensing,reports}[state.page]||home)();}
 function bind(){
  document.querySelector('#newBill')?.addEventListener('click',()=>{
   if(!can('billing'))return;
   const list=visits();if(!list.length){toast('Cần có lượt khám để lập phiếu phí.');return;}
   form('Lập phiếu phí','Phiếu lưu giá tại thời điểm lập, không hiển thị nội dung bệnh án.',`<label>Người bệnh / lượt khám *<select name="visitId">${list.map(({p,v})=>`<option value="${v.id}">${esc(p.name)} · ${esc(p.id)} · ${esc(v.id)}</option>`).join('')}</select></label><label>Dịch vụ *<select name="serviceId">${ws().services.map(s=>`<option value="${s.id}">${esc(s.name)} · ${money(s.price)}</option>`).join('')}</select></label>`+input('quantity','Số lượng *','1','type="number" min="1" max="100" step="1" required'),'billing',f=>{
    const pair=visits().find(({v})=>v.id===f.visitId),service=ws().services.find(s=>s.id===f.serviceId),quantity=Number(f.quantity);if(!pair||!service||!Number.isInteger(quantity)||quantity<1||quantity>100)throw Error('Lượt khám, dịch vụ hoặc số lượng không hợp lệ.');
    ws().bills.push({id:'PT-'+crypto.randomUUID().slice(0,8).toUpperCase(),patientId:pair.p.id,visitId:pair.v.id,items:[{serviceId:service.id,name:service.name,price:service.price,quantity}],status:'unpaid',transactions:[],created:new Date().toISOString(),author:author()});persist('Đã lập phiếu phí mẫu.');
   });
  });
  document.querySelector('#newService')?.addEventListener('click',()=>{if(!can('prices'))return;form('Thêm dịch vụ mẫu','Giá là số nguyên VND.',input('name','Tên dịch vụ *','','required maxlength="100"')+input('price','Đơn giá VND *','','type="number" min="1" max="100000000" step="1" required'),'prices',f=>{const price=Number(f.price);if(!f.name.trim()||!Number.isSafeInteger(price)||price<1||price>100000000)throw Error('Tên hoặc giá không hợp lệ.');ws().services.push({id:'DV-'+crypto.randomUUID().slice(0,8),name:f.name.trim(),price});persist('Đã thêm dịch vụ vào bảng giá mẫu.');});});
  document.querySelectorAll('[data-pay-bill]').forEach(b=>b.onclick=()=>{if(!can('billing'))return;const bill=ws().bills.find(x=>x.id===b.dataset.payBill);form('Thu tiền',bill.id+' · Còn phải thu '+money(billTotal(bill)-sumPaid(bill)),input('amount','Số tiền VND *',billTotal(bill)-sumPaid(bill),'type="number" min="1" step="1" required')+'<label>Phương thức<select name="method"><option>Tiền mặt</option><option>Chuyển khoản</option><option>Thẻ</option></select></label>','billing',f=>{addPayment(bill,f,author());persist('Đã ghi giao dịch thu tiền mẫu.');});});
  document.querySelectorAll('[data-refund-bill],[data-cancel-bill]').forEach(b=>b.onclick=()=>{if(!can('billing'))return;const bill=ws().bills.find(x=>x.id===(b.dataset.refundBill||b.dataset.cancelBill)),refund=!!b.dataset.refundBill;form(refund?'Hoàn tiền phiếu thu':'Hủy phiếu phí',bill.id+' · Giữ lại giao dịch và lý do trong lịch sử.',area('reason','Lý do *'),'billing',f=>{if(refund)refundBill(bill,f.reason,author());else{if(bill.status!=='unpaid'||!f.reason.trim())throw Error('Chỉ hủy phiếu chưa thu và cần lý do.');bill.status='cancelled';bill.cancelReason=f.reason.trim();}persist(refund?'Đã ghi hoàn tiền mẫu.':'Đã hủy phiếu phí mẫu.');});});
  document.querySelectorAll('[data-print-bill]').forEach(b=>b.onclick=()=>{if(!can('receipts'))return;const bill=ws().bills.find(x=>x.id===b.dataset.printBill),p=repo.patients.find(x=>x.id===bill.patientId);printDocument('PHIẾU THU MẪU',p,`<p>${esc(bill.id)} · Lượt ${esc(bill.visitId)} · ${billLabels[bill.status]}</p>${table(['DỊCH VỤ','SL','ĐƠN GIÁ','THÀNH TIỀN'],bill.items.map(i=>`<tr><td>${esc(i.name)}</td><td>${i.quantity}</td><td>${money(i.price)}</td><td>${money(i.quantity*i.price)}</td></tr>`).join(''))}<p>Tổng phí: ${money(billTotal(bill))} · Thu ròng: ${money(sumPaid(bill))}</p><p>Không thay thế hóa đơn điện tử.</p>`);});
  document.querySelectorAll('[data-lab-result]').forEach(b=>b.onclick=()=>{
   if(!can('results'))return;const pair=assignedOrders().find(({o})=>o.id===b.dataset.labResult);if(!pair||pair.v.status==='closed'||pair.o.result?.state==='final')return;const {p,v,o}=pair,r=o.result||{};
   form('Ghi kết quả chỉ định',p.name+' · '+p.id+' · '+v.id+' · '+o.name,area('value','Kết quả / báo cáo *',r.value)+input('unit','Đơn vị',r.unit)+input('reference','Khoảng tham chiếu từ nguồn',r.reference)+'<label>Trạng thái<select name="state"><option value="preliminary">Sơ bộ</option><option value="final">Hoàn tất</option></select></label>'+input('file','Báo cáo đính kèm (tùy chọn)','','type="file" accept="application/pdf,image/png,image/jpeg"')+'<label class="full checkbox-label"><input type="checkbox" name="confirmed">Đã đối chiếu người bệnh, chỉ định và nguồn kết quả (demo).</label>','results',async(f,form,guard)=>{
    let attachment;const file=form.querySelector('[name=file]').files[0];
    if(file){if(!['application/pdf','image/png','image/jpeg'].includes(file.type)||file.size>1048576)throw Error('Báo cáo chỉ nhận PDF / PNG / JPEG, tối đa 1 MB.');attachment={name:file.name,type:file.type,data:await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(Error('Không đọc được tệp.'));reader.readAsDataURL(file);})};}
    guard();if(o.assignedTo!==state.accountId||v.status==='closed'||o.result?.state==='final')throw Error('Chỉ định ngoài phạm vi, đã hoàn tất hoặc lượt đã đóng.');
    recordResult(o,{...f,confirmed:f.confirmed==='on'},author());if(attachment)o.result.attachment=attachment;persist('Đã lưu kết quả CLS mẫu theo chỉ định được giao.');
   });
  });
  document.querySelectorAll('[data-print-result]').forEach(b=>b.onclick=()=>{if(!can('results'))return;const pair=assignedOrders().find(({o})=>o.id===b.dataset.printResult);if(!pair?.o.result)return;const {p,v,o}=pair;printDocument('PHIẾU KẾT QUẢ MẪU',p,`<p>${esc(o.name)} · ${esc(o.id)} · ${esc(v.id)}</p><p class="pre-wrap">${esc(o.result.value)} ${esc(o.result.unit)}</p><p>Khoảng tham chiếu: ${esc(o.result.reference||'Chưa cung cấp')}</p><p>Trạng thái: ${o.result.state==='final'?'Hoàn tất':'Sơ bộ'} · ${esc(o.result.author)}</p>`);if(o.result.attachment){const button=document.createElement('button');button.textContent='Xem báo cáo đính kèm';button.onclick=()=>viewAttachment(o.result.attachment);document.querySelector('#modal .form-actions').prepend(button);}});
  document.querySelectorAll('[data-view-rx],[data-dispense]').forEach(b=>b.onclick=()=>{
   if(state.role!=='pharmacy'||!session()?.active||!accountRoles(session()).includes('pharmacy'))return;const pair=prescriptions().find(({rx})=>rx.id===(b.dataset.viewRx||b.dataset.dispense));if(!pair)return;const {p,v,rx}=pair;
   const body=table(['THUỐC','CÁCH DÙNG','SỐ LƯỢNG'],rx.medications.map(m=>`<tr><td>${esc(m.name)}</td><td class="wrap-cell pre-wrap">${esc(medicationInstructions(m))}</td><td>${esc(m.quantity)} ${esc(m.unit)}</td></tr>`).join(''))+`<p>${esc(rx.author)} · ${esc(v.id)}</p><p class="pre-wrap">Dặn dò: ${esc(rx.plan||'Chưa ghi trong bản đơn đã xác nhận')}</p>${v.closure?.kind==='cancelled'?'<p class="error">Lượt đã hủy / bỏ về. Đơn chỉ đọc, không được ghi cấp thuốc.</p>':''}`;
   if(!b.dataset.dispense){printDocument('ĐƠN THUỐC MẪU',p,body);return;}
   if(!can('dispense')||!dispensable(pair))return;
   form('Đối chiếu & cấp thuốc',p.name+' · '+p.id+' · '+rx.id,`<div class="full">${body}</div><label class="full checkbox-label"><input name="confirmed" type="checkbox" required>Đã đối chiếu người bệnh, đơn, thuốc và số lượng (demo).</label>`+area('note','Ghi chú cấp thuốc *'),'dispense',f=>{if(!dispensable(pair)||f.confirmed!=='on')throw Error('Đơn đã cấp hoặc chưa xác nhận đối chiếu.');rx.status='dispensed';rx.dispensing={created:new Date().toISOString(),author:author(),note:f.note.trim(),medications:structuredClone(rx.medications)};persist('Đã ghi nhận cấp thuốc mẫu, giữ nguyên đơn bác sĩ.');});
  });
  document.querySelector('#reportDate')?.addEventListener('change',e=>{state.reportDate=e.target.value;ctx.render();});
  document.querySelector('#printReport')?.addEventListener('click',()=>{if(!can('reports'))return;const day=state.reportDate||localDate().slice(0,10),d=reportData(day);printDocument('BÁO CÁO NGÀY '+day,null,table(['CHỈ SỐ','GIÁ TRỊ'],[['Lượt mở',d.opened],['Lượt hoàn tất',d.finished],['Hủy / bỏ về',d.cancelled],['Tổng thu',money(d.income)],['Tổng hoàn',money(d.refund)],['Thu ròng',money(d.income-d.refund)]].map(([a,b])=>`<tr><td>${a}</td><td>${b}</td></tr>`).join('')));});
 }
 return {home,page,bind,printDocument,viewAttachment};
}
